### ISSUE TITLE
embeddings.load('/content/my-embeddings/')

### ISSUE THREAD

**Issue by edanweis** [neuml/txtai#105]
Using Google Colab to load saved embeddings returns the below error. Is there a workaround to Google Colab (python 3.6 which only supports protocol 4? 

See, [SO Post](https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5)

```python
ValueError                                Traceback (most recent call last)
<ipython-input-7-6bc7130df1be> in <module>()
      2 import pickle5 as pickle
      3 
----> 4 embeddings.load('/content/my-embeddings/')

/usr/local/lib/python3.7/dist-packages/txtai/embeddings/base.py in load(self, path)
    305         # Index configuration
    306         with open("%s/config" % path, "rb") as handle:
--> 307             self.config = pickle.load(handle)
    308 
    309             # Build full path to embedding vectors file

ValueError: unsupported pickle protocol: 5
```

**Comment by edanweis** [comment]
I now see the same error running Python 3.7 locally.

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue. These embeddings must have been built on Python 3.8+ 

The code currently defaults to the highest protocol available but there was a new protocol added with Python 3.8, will take a look at a fix to handle this case in the next release. 

Meanwhile, a workaround to get you moving forward (backup your index and run the following).

```
pip install pickle5
```

```python

import pickle5 as pickle
with open("/content/my-embeddings/config", "rb") as f:
  config = pickle.load(f)

with open("/content/my-embeddings/config", "wb") as f:
  pickle.dump(config, f, protocol=4)
```
