### ISSUE TITLE
Multilingual CLIP with M-CLIP/M-BERT-Base-ViT-B

### ISSUE THREAD

**Issue by edanweis** [neuml/txtai#106]
I am trying to index embeddings with a multilingual clip model, following [Huggingface M-BERT-Base-ViT-B instructions](https://huggingface.co/M-CLIP/M-BERT-Base-ViT-B).  After downloading weights and running my code from within the [Multilingual-CLIP](https://github.com/FreddeFrallan/Multilingual-CLIP) repository. 

````Python
embeddings = Embeddings({"method": "transformers", "path": "M-CLIP/M-BERT-Base-ViT-B"})
embeddings.index(images())
````

But getting the following error. 

```Python
Traceback (most recent call last):
  File "/home/ec2-user/Multilingual-CLIP/17-08-21-embed.py", line 72, in <module>
    process()
  File "/home/ec2-user/Multilingual-CLIP/17-08-21-embed.py", line 66, in process
    embeddings.index(images())
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/embeddings/base.py", line 76, in index
    ids, dimensions, embeddings = self.vectors(documents)
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/embeddings/base.py", line 399, in vectors
    ids, dimensions, stream = self.model.index(documents)
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/vectors/transformers.py", line 63, in index
    uids, dimensions = self.batch(batch, output)
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/vectors/transformers.py", line 90, in batch
    embeddings = self.model.encode(documents)
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/vectors/pooling.py", line 63, in encode
    lengths = np.argsort([-len(x) for x in documents])
  File "/home/ec2-user/miniconda3/envs/txtai/lib/python3.9/site-packages/txtai/vectors/pooling.py", line 63, in <listcomp>
    lengths = np.argsort([-len(x) for x in documents])
TypeError: object of type 'JpegImageFile' has no len()
```

Could this be related to requiring embeddings with MEAN pooling?

**Comment by edanweis** [comment]
According to [sentence-transformers multilingual image example](https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/image-search/Image_Search-multilingual.ipynb) it appears `clip-ViT-B-32-multilingual-v1` is used to encode the query, and `clip-ViT-B-32` is used for images. 

Maybe a useful feature for txtai, would be to specify an optional query model in the search function?

Or can that be already be acheived using a pipeline?

**Comment by davidmezzetti** [comment]
That is an interesting one. This is the only case I'm aware of where the model to index and query could potentially be different. The best way to accomplish this right now would be something like this:

```python
# Index images
embeddings = Embeddings({"method": "sentence-transformers", "path": "clip-ViT-B-32"})
embeddings.index(images())

# Update model at query time to support multilingual queries
embeddings.config["path"] = "clip-ViT-B-32-multilingual-v1"
embeddings.model = embeddings.loadVectors()
```

If this use case became more common than this one model, a new method to update the vector model after indexing could be helpful.

**Comment by edanweis** [comment]
Ok, I tried "Green Tree" and 绿树 (green tree), but the result is a very different image. It's the same with any non english text, which suggests the model is not being updated?

```Python
embeddings = Embeddings()
embeddings.load('image-embeddings')
# Update model at query time to support multilingual queries
embeddings.config["path"] = 'clip-ViT-B-32-multilingual-v1'
embeddings.model = embeddings.loadVectors()

for query in ["green tree", "绿树"]:
    for result in embeddings.search(query, 1):
        index, _ = result
        print(index, query)
```

**Comment by davidmezzetti** [comment]
Just updated the examples and was able to get the multilingual model working.

https://github.com/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb
https://github.com/neuml/txtai/blob/master/examples/images.py

I used the models from the Hugging Face Model Hub, possible that made a difference?

**Comment by edanweis** [comment]
Thanks @davidmezzetti. I can confirm that's working for me, although not when loading embeddings created in previous versions of txtai #104
