### ISSUE TITLE
Get multiple translation candidates in translation pipeline

### ISSUE THREAD

**Issue by j0st** [neuml/txtai#113]
Hello,

is it possible to get (for example) the best five translation results from the Hugging Face models or only one translation for a single sentence?

**Comment by davidmezzetti** [comment]
Currently, there is only a single translation as the pipeline is designed to work in automated workflows. You can use a segmentation pipeline to split text into sentences before running it through translation. The following is an example.

```python
from txtai.pipeline import Segmentation, Translation
from txtai.workflow import Task, Workflow

segment = Segmentation(sentences=True)
translate = Translation()

tasks = [
    Task(segment),
    Task(lambda x: translate(x, "fr"))
]

data = [
    "This is a test with two sentences. The data will be split into two results."
]

# Workflow that translates text to French
workflow = Workflow(tasks)

# Run workflow
for x in workflow(data):
    print(x)

```

Prints

```
C'est un test avec deux phrases.
Les données seront divisées en deux résultats.
```

This example covers workflows in more detail - https://colab.research.google.com/github/neuml/txtai/blob/master/examples/14_Run_pipeline_workflows.ipynb

**Comment by davidmezzetti** [comment]
Please re-open if additional information is needed and/or this didn't help.
