### ISSUE TITLE
Integrate FastAPI for model serving

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#12]
Add pattern for serving models. API should be driven by a configuration yaml file listing the model name and path.

API endpoints:

- /$model/search?q=value
    - Runs a search against _model_ for query _q_
- /$model/similarity?t1=text&t2=text
    - Compares _t1_ and _t2_ for similarity using _model_
- /$model/embedding?t=text
   - Builds a sentence embeddings vector for text stored in _t_

**Comment by davidmezzetti** [comment]
As noted in issue #12, transformer embedding models should be pre-loaded in the API to prevent lag on the first invocation of the API

**Comment by Fanchouille** [comment]
With FastAPI you could use on startup event, see here : https://fastapi.tiangolo.com/advanced/events/
It should do the trick and dowload/load models before the first invocation.
