### ISSUE TITLE
Integration with a hosted vector search DB.

### ISSUE THREAD

**Issue by ydennisy** [neuml/txtai#133]
Hi @davidmezzetti 

Sorry for the multiple questions!

I was wondering if you have a doc or any suggestions for how best to integrate this lib with a hosted vector search engine?

Best,
Dennis

**Comment by davidmezzetti** [comment]
No problem. This can be done as follows:

```python

from txtai.embeddings import Embeddings

embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2"})

vectors = embeddings.batchtransform(documents)

# Load vectors into hosted vector db
```

The batch transform method has room for improvement in terms of the runtime performance but this would accomplish the task functionally.

**Comment by davidmezzetti** [comment]
Please feel free to re-open or open a new issue should you have further questions

**Comment by mingfang** [comment]
I see there's a repo for integrating with Weaviate here https://github.com/neuml/txtai.weaviate.
I'm looking for more integrations such as with 
qdrant https://github.com/qdrant/qdrant
and milvus https://github.com/milvus-io/milvus

Is the plan to have an "official" set of integrations?

**Comment by davidmezzetti** [comment]
Hello - yes the plan is to provide example projects on integrating with external vector storage engines. The repo for Weaviate integration shows how a workflow can be used to encode embeddings and read/write/search vectors with Weaviate.
