### ISSUE TITLE
Add korean translation to README.md

### ISSUE THREAD

**Issue by 0206pdh** [neuml/txtai#138]
Hi! ! I'm South Korean and I want to help you translate README.md to Korean.
Is it okay to translate your README.md?
Thank you.

**Comment by davidmezzetti** [comment]
Thank you for the offer, feel free to submit a pull request!

The only thing to note is that the README does change frequently, so it could get stale fast. It would be interesting to see how machine translation would do.

**Comment by abhishekkshk68** [comment]
Hi David,


How to few shot training with the API?
Example of zero shot is provided, but not sure about few shots training
from scratch.

Thanks
Abhi
