### ISSUE TITLE
Few shot training with API?

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#143]
@abhishekkshk68 - Adding a new issue for this question. 

------

Hi David,

How to few shot training with the API?
Example of zero shot is provided, but not sure about few shots training
from scratch.

Thanks
Abhi

**Comment by abhishekkshk68** [comment]
Thanks a million, David
I will check it out.

**Comment by davidmezzetti** [comment]
Sounds good, feel free to re-open or open a new issue should you have further questions
