### ISSUE TITLE
（2nd） can't download articles.sqlite 

### ISSUE THREAD

**Issue by takky0330** [neuml/txtai#15]
Oh, my...
Also, code 403 has prevented you from downloading...

Next time, save it locally so you can download it again.
Please.

**Comment by davidmezzetti** [comment]
Sorry for the continued issues with that file. I have updated the notebooks to host the file on github, the link will no longer expire.

**Comment by takky0330** [comment]
Thank you very much.
I was able to download it. I've saved it locally as well!
