### ISSUE TITLE
Docker run timeout when downloading embeddings files

### ISSUE THREAD

**Issue by fils** [neuml/txtai#16]
So, I'm very new to this but I have been able to put something together with txtai.  Thanks for that!  Very interesting stuff.

I built a new index and saved it, then worked up a simple flask app to load it and interface to it.  

However, the initial embeddings line in there has to download the models from the net and this causes a timeout when trying to fire up the resulting container in Docker.   Is there a way to pre-download these files and then point to those rather than having it try and load them?    It seems to do this on my local machine, but I can not find where they are or how to reference them.  

app.py
```
import os, json, requests
import urllib.request
from flask import Flask, abort, request, jsonify
from flask import Response
from flask_cors import CORS
from flask_restful import Resource, Api
from txtai.embeddings import Embeddings

# Create embeddings model, backed by sentence-transformers & transformers
embeddings = Embeddings({"method": "transformers", "path": "sentence-transformers/bert-base-nli-mean-tokens"})
embeddings.load("index")

app = Flask(__name__)

cors = CORS(app, resources={r"/*": {"origins": "*"}})
app.config['CORS_HEADERS'] = 'Content-Type'

@app.route("/q1",  methods=['GET'])
def serch():
    q = request.args.get('q')
    results = embeddings.search(q, 10)
    data = {}  # build json from the set..
    for r in results:
        uid = r[0]
        score = r[1]
        data[str(uid)] = score
        #   print('score:{} -- {}'.format(score, text_corpus[uid]))
        print('score:{} -- {}'.format(score, uid))
    j = json.dumps(data)
    return  j

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))
```

Dockerfile
```
# Use the official Python image.
# https://hub.docker.com/_/python
FROM python:3.7

# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

# Install production dependencies.
RUN pip install Flask gunicorn
RUN pip install flask_restful
RUN pip install flask-cors
RUN pip install numpy
RUN pip install txtai

# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available.
#CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app
CMD exec gunicorn --bind :8080 --workers 1 --threads 8 app:app
```

**Comment by davidmezzetti** [comment]
Thank you for using txtai, glad to hear you're seeing positive results so far.

Regarding the pre-load, one way to do this with the current architecture is to add the following to the beginning of app.py

```
from transformers import AutoModel
AutoModel.from_pretrained("sentence-transformers/bert-base-nli-mean-tokens")
```

As a side note, there is a task to integrate FastAPI (#12) to add similar functionality to what you're working on. I'll add a note referencing this issue to have a direct way to preload the transformer libraries.

**Comment by fils** [comment]
@davidmezzetti Thanks..   I tried to add what you mentioned, but I get the same issue...

I should have added the error to the previous post.. sorry for not doing that..  

error:
```

[fils@fedora simpleservice]$ podman run -i -p8080:8080 0becb36e1ede
[2020-08-26 17:19:19 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-08-26 17:19:19 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2020-08-26 17:19:19 +0000] [1] [INFO] Using worker: threads
[2020-08-26 17:19:19 +0000] [4] [INFO] Booting worker with pid: 4
Downloading: 100%|██████████| 461/461 [00:00<00:00, 219kB/s]
Downloading:  53%|█████▎    | 233M/438M [00:27<00:22, 9.15MB/s][2020-08-26 17:19:49 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:4)
[2020-08-26 17:19:49 +0000] [4] [INFO] Worker exiting (pid: 4)
Downloading:  53%|█████▎    | 233M/438M [00:27<00:23, 8.60MB/s]
[2020-08-26 17:19:49 +0000] [15] [INFO] Booting worker with pid: 15
Downloading:   2%|▏         | 7.48M/438M [00:00<00:51, 8.40MB/s]^C[2020-08-26 17:19:52 +0000] [1] [INFO] Handling signal: int
[2020-08-26 17:19:52 +0000] [15] [INFO] Worker exiting (pid: 15)
Downloading:   2%|▏         | 8.07M/438M [00:01<00:56, 7.67MB/s]
[2020-08-26 17:19:52 +0000] [1] [INFO] Shutting down: Master
```

So since the container is a brand new environment it still tries to download the needed files (there seems to be 5).   This is what is timing out.  
This is podman in Fedora, but I get the same issue with vanilla Docker in Ubuntu.

I need someway to download these so I can include them in the Docker image file for the code to reference directly rather than pulling down on first launch.   This would be particularly needed for any lambda/cloud function implementation too.  

Thanks for the help..
wanting to push this out to show to my community to get them engaged in a discussion on semantic search!

**Comment by davidmezzetti** [comment]
I don't have a lot of experience with Flask but maybe something like this would help:

```python
from transformers import AutoModel

@app.before_first_request
def initialize():
  AutoModel.from_pretrained("sentence-transformers/bert-base-nli-mean-tokens")
```

Alternatively, can you add a separate RUN command after installing txtai?

```
RUN python -c 'from transformers import AutoModel; AutoModel.from_pretrained("sentence-transformers/bert-base-nli-mean-tokens")'
```

**Comment by fils** [comment]
@davidmezzetti Thanks..   I'll give those a shot later today!

I like the RUN command idea...   I'd think that would work and would be a neat trick.  It would seem it would pull the files into the copied context.  I'll try it out.  

I'm not locked into Flask, so if FastCGI or some other approach seems better to you I'm all ears.  
When I try these I will report back.

**Comment by fils** [comment]
@davidmezzetti 

The RUN command you suggested to place in the Dockerfile did the trick.   It pulls down the large file and stages it into the image.   When I do I run a container there are still 3 files that are downloaded, but they are small.  

```
podman run -i -p8080:8080 5004e73ea400
[2020-08-26 22:46:04 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-08-26 22:46:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2020-08-26 22:46:04 +0000] [1] [INFO] Using worker: threads
[2020-08-26 22:46:04 +0000] [4] [INFO] Booting worker with pid: 4
Downloading: 100%|██████████| 232k/232k [00:00<00:00, 1.74MB/s]
Downloading: 100%|██████████| 2.00/2.00 [00:00<00:00, 797B/s]
Downloading: 100%|██████████| 112/112 [00:00<00:00, 42.1kB/s]
```

This is still problematic for lambda services....   but I'm not interested in those anyway. ;)  

So this seems to do the trick for me.   Thanks for the help and suggestions.   At some point it would be good to have a process that doesn't require any file downloads at the point the server is fired up.  For me at this point to do some evaluations, this is enough though.

Thanks again..  looking forward to exploring txtai more....

**Comment by davidmezzetti** [comment]
Glad you were able to get it working, please let me know how your exploration with txtai goes. I'll go ahead and close this issue.

Regarding Lambda, here is an article that might help - https://towardsdatascience.com/serverless-bert-with-huggingface-and-aws-lambda-625193c6cc04

The model files are locally stored in ~/.cache/torch/transformers but Lambda functions have a size limit. This article suggests storing the model in S3 and loading it from there.
