### ISSUE TITLE
KeyError on translating lists with more than 36 words to languages other than English

### ISSUE THREAD

**Issue by sarthakrastogi** [neuml/txtai#165]
I get the following error when I try to translate lists more than 36 words long.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-39-bd26a2689479> in <module>()
      1 translate = Translation(gpu=True, batch=32)
----> 2 k_trans = translate(a, dest_language_code)

4 frames
/usr/local/lib/python3.7/dist-packages/transformers/models/m2m_100/tokenization_m2m_100.py in get_lang_token(self, lang)
    352 
    353     def get_lang_token(self, lang: str) -> str:
--> 354         return self.lang_code_to_token[lang]
    355 
    356     def get_lang_id(self, lang: str) -> int:

KeyError: None
```

Trying different batch size and list size combinations isn't helping either. Please advise.

**Comment by davidmezzetti** [comment]
It looks like language detection is running into an issue for at least one of the words. The language detection works best with longer sequences.

What would be the desired functionality in this case? It could skip over the rows with no language detected and not translate for example. Do you have example data you could provide?

**Comment by davidmezzetti** [comment]
If there are further questions, please feel free to reopen or open a new issue.
