### ISSUE TITLE
Add batch search

### ISSUE THREAD

**Issue by Fanchouille** [neuml/txtai#18]
First of all, thanks a lot for your work, it's really great !
In order to user the search on lots of documents, it would be great if we could :

- [ search batches of elements] : embeddings.search(queries, top_k) which would return a list of top_k results for each query in queries
- [use fastest lib to do so  ]  (I use hnsw implem of [nmslib](https://github.com/nmslib/nmslib) which provides a batch search and great implementation of hnsw).

Keep up the good work !

**Comment by davidmezzetti** [comment]
Thank you for the suggestion and kind words! Will look into batch search.

Regarding nmslib, the reason I went with the header library was that nmslib was fuzzy on the license. It mentioned a core piece was GPL. I'll research this further.

**Comment by Fanchouille** [comment]
Thanks for your answer
Sorry I did not look a the license issue.

As hnswlib is created by the same team, it provides batched queries with knn_query : 
![image](https://user-images.githubusercontent.com/17620116/91581047-3d192380-e94e-11ea-93bd-d9e6a646e516.png)

I believe Faiss supports it the same way by juste passing matrix queries instead of vector query.
Annoy doesn't seem to expose such a functionnality.

**Comment by davidmezzetti** [comment]
Better late than never but this is addressed in v2.0 of txtai
