### ISSUE TITLE
ImportError: Language detection is not available - install "pipeline" extra to enable while trying to translate

### ISSUE THREAD

**Issue by gkhlevtov** [neuml/txtai#194]
Hello! I was trying to translate text for two days. The first day It worked awesomely, but the next day there I meet with ImportError.
Here are the blocks of my code: (_P.S. I'm launching all of this in Google Colab Notebook_)
>%%capture 
!pip install git+https://github.com/neuml/txtai 

>%%capture
from txtai.pipeline import Translation
translate = Translation()

>translation = translate("This is a test translation into Spanish", "es")
translation

And the error screenshot:
![sc](https://user-images.githubusercontent.com/71844829/147755561-b5dd3887-d675-4f83-a782-ff91b3590590.png)

**Could you tell me how to "install "pipeline" extra", please?**

**Comment by davidmezzetti** [comment]
Thank you for giving txtai a try! 

You can install extras with pip `pip install txtai[pipeline]`

More details: https://neuml.github.io/txtai/install/#pipeline

**Comment by gkhlevtov** [comment]
Thanks for your help! Now everything works fine.
