### ISSUE TITLE
Conclusion on why zero shot learning is used for semantic similarity

### ISSUE THREAD

**Issue by numan619** [neuml/txtai#205]
Siamese network-based semantic similarity models are supposed to work better than zero shot based MNLI models.
Can someone please help me understand why zero shot based semantic search is used instead of a finetuned semantic similarity model.

**Comment by davidmezzetti** [comment]
Hello - thank you for putting the question in. 

Would you mind elaborating more on your question? The default models are backed by [sentence-transformers](https://github.com/UKPLab/sentence-transformers) and can be found on the [HF Hub](https://huggingface.co/models?pipeline_tag=sentence-similarity&sort=downloads).

There is a zero-shot classifier as part of the labels pipeline, which does use MNLI models but that isn't used as part of the Embeddings module, which is where semantic search is happening. There is also the concept of re-ranking (cross-encoders in sentence-transformers) but that is designed to work with a set of results.

**Comment by numan619** [comment]
Can you please help me understand which transformers pipeline and model does the `Similarity()` pipeline uses?

**Comment by davidmezzetti** [comment]
The `Similarity()` pipeline is a re-ranker/cross-encoder and uses text classification models (it works with fixed labels and zero-shot MNLI models).

Indexable semantic search functionality is provided by [Embeddings](https://neuml.github.io/txtai/embeddings/). The Embeddings instance also has a `similarity` method which uses the transformer models mentioned above.

In most if not all cases, I've found that the MNLI models/re-rankers work better but they don't scale to large amounts of data. Peeling back how the models differ, it does make sense. The MNLI models feed both pieces of text to the transformer model and return a similarity output. The bi-encoder computes embeddings independently and compares the results with a similarity function (dot or cosine similarity). 

sentence-transformers has a great page on this - https://www.sbert.net/examples/applications/cross-encoder/README.html

**Comment by numan619** [comment]
Thank you so much for the clarification :slightly_smiling_face:

**Comment by davidmezzetti** [comment]
No problem
