### ISSUE TITLE
TypeError when trying to index content data from list of tuples

### ISSUE THREAD

**Issue by nickkimer** [neuml/txtai#219]
Hi! I am trying to build an embeddings index with a list of tuples from pandas.DataFrame.itertuples() and I am getting this error. It works when I only provide a flat list of strings but trying to add additional information throws this error. 

I am trying to follow along in the guide like so:
```
# Create an index for the list of text
embeddings.index([(uid, {"text": text, "length": len(text)}, None) for uid, text in enumerate(data)])
``` 

And here is my version:
```
embeddings = Embeddings({"path": "sentence-transformers/all-mpnet-base-v2","backend": "faiss","content": True,"objects":True})

upsert_data = list(df.itertuples())
embeddings.index([(t.Index, { "text":t.text, "first_name":t.first_name, "last_name":t.last_name}, None) for t in upsert_data])
```
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by davidmezzetti** [comment]
Hi Nick - Thanks for giving txtai a try!

I've looked at the example. Do you happen to have a data frame filter operation on `df`? That type error looks like a Pandas error. I've seen similar when say filtering an int column and encountering a None entry.

Running the following code works for me:

```python
import json
import pandas as pd
from txtai.embeddings import Embeddings

embeddings = Embeddings({"path": "sentence-transformers/all-mpnet-base-v2", "backend": "faiss", "content": True, "objects": True})

df = pd.DataFrame([("test", "first", "last", None)] * 50, columns=["text", "first_name", "last_name", "none_column"])

upsert_data = list(df.itertuples())
embeddings.index([(t.Index, {"text": t.text, "first_name": t.first_name, "last_name": t.last_name}, None) for t in upsert_data])
print(embeddings.search("select * from txtai", 1))
```

But if I add a filter to the data frame:

```python
df = df[df["none_column"] > 1]

upsert_data = list(df.itertuples())
embeddings.index([(t.Index, {"text": t.text, "first_name": t.first_name, "last_name": t.last_name}, None) for t in upsert_data])
print(embeddings.search("select * from txtai", 1))
```

I get:

```
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

I believe even when wrapping the itertuples operation with a list, it is lazily resolved, so the stack trace would still show the error coming from the `embeddings.index` call.

That's my best guess as to what's going on. If that doesn't work and you have a couple example rows you can share, I'm happy to help debug further.

**Comment by davidmezzetti** [comment]
One additional idea/thing to check - is the data frame empty?

**Comment by nickkimer** [comment]
Hi @davidmezzetti , thank you so much for your prompt reply and assistance. You were exactly right, there was a filter on the dataframe that caused some null values in the documents list inside of the itertuples() object. It's working as expected!

**Comment by davidmezzetti** [comment]
No problem, this did expose a problem with processing empty document collections, I appreciate you reporting this.

I'm going to go ahead and close the issue. Please open new issues if you have additional questions or run into unexpected problems.
