### ISSUE TITLE
grab a object in index by id?

### ISSUE THREAD

**Issue by luquitared** [neuml/txtai#264]
Hello!

Is it possible to retrieve an object by the ID? Something like:
``` python
    def get_by_id(self, id):
        return embeddings.search("select * from txtai where id = " + str(id))
```

thanks

**Comment by davidmezzetti** [comment]
Hello, thank you for asking.

This is possible. An example is shown below.

```python
return embeddings.search("select object from txtai where id = 'value' limit 1")[0]["object"]
```

This assumes content and object storage are both enabled in the embeddings index. 

A more complete example can be found in this notebook.

https://colab.research.google.com/github/neuml/txtai/blob/master/examples/24_Whats_new_in_txtai_4_0.ipynb#scrollTo=lGmiYXyqyjtQ

**Comment by luquitared** [comment]
Here is my current function
``` python
def get_by_id(self, id):
        query = "select text from txtai where id = " + str(id) + " limit 1"
        print(query)
        return embeddings.search(query)
```

My output looks like:
``` bash
vscode ➜ /workspaces/vectotron/parse_rabbit (main ✗) $ python3 explore.py 
select text from txtai where id = 22 limit 1
[]
```

I for sure have a lot of objects indexed and am loading the index before search. I tried adding single quotes on 'value' and also tried selecting * instead of just 'text'

Thanks for all the support again thus far.

**Comment by davidmezzetti** [comment]
What do you get if you run:

```python
embeddings.search("select * from txtai")
```

Assuming the index has data, it should give you 3 random documents.

**Comment by luquitared** [comment]
hmm.. it appears empty. must be something with the way I have structured my code.

manager.py
``` python
from txtai.embeddings import Embeddings
embeddings = Embeddings(
    {"path": "sentence-transformers/nli-mpnet-base-v2", "content": True, "objects": True})


class Manager:
    def __init__(self, index_name):
        self.index_name = index_name

    def search(self, query_text, k):
        embeddings.load(self.index_name)
        return embeddings.search(query_text, k)

    def count(self):
        embeddings.load(self.index_name)
        print(embeddings.exists(path=self.index_name))
        return embeddings.count()

    def index(self, documents):
        embeddings.index([(uid, text, None)
            for uid, text in enumerate(documents)])
        embeddings.save(self.index_name)
        return True

    def delete(self, id):
        return embeddings.delete(id)

    def get_by_id(self, id):
        query = "select * from txtai"
        print(query)
        return embeddings.search(query)
```

explore.py (file i am running)
``` python
from manager import Manager

instance = Manager("imessage")

#print(instance.count())
#print(instance.delete([0]))
#print(instance.search('test', 10))
print(instance.get_by_id('22'))
```

**Comment by luquitared** [comment]
Oops. I lied to you. I did not load the index after reading my post here. Sorry! 

PS. I sent you a message via Linkedin. I have a couple questions and would love to contribute a PR.
