### ISSUE TITLE
Crossplatform problem running txtai in Windows 10 [WinError 32]

### ISSUE THREAD

**Issue by luisArandas** [neuml/txtai#267]
Hello!
First of all, thanks for this amazing project.

I'm getting this error while trying to run some code (which is perfect on a `Macbook Pro mid 2015 - Monterey v12.2`). After creating audio embeddings and trying to save the compressed file I just got the following bug (it saves anyway).

```
  File "C:\Python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LUISAR~1\\AppData\\Local\\Temp\\tmpw_5ft63f\\documents'
```

Now as it worked, I tried to load the embeddings and try to search them, and I get exactly the same error, after getting the first result. So this might seem that some processes are still running even when the library tries to do something else? Or do you think this is a Python problem? 

Thanks in advance

**Comment by davidmezzetti** [comment]
Thank you for trying txtai and the kind words!

Can you describe more on what steps you were taking? Were these errors after indexing and saving only? Are you able to run more follow on searches without that error coming up again? Is your embeddings index configured with `content: True`? 

I've seen this issue with some of the unit tests on Windows in the past. There is a race condition between when Windows actually closes the underlying SQLite file (even when the connection is closed, the file isn't released until GC occurs) and when the TemporaryDirectory tries to delete it. 

What version of Python are you using? It seems like later version of Python handle deleting temporary directories more gracefully.

**Comment by luisArandas** [comment]
Hi @davidmezzetti! 

So the steps are very simple. I just start by activating my environment and run a script to generate the embeddings. I create an `Embeddings` object and treat the csv data to be able to go there. Then I index, which goes fine (I think!)` -> audio_embeddings.index([(uid, text, None) for uid, text in enumerate(audio_data)])` and then just save` -> audio_embeddings.save("embeddings/audio/audio.tar.xz")` in a compressed format. I think the problem is in the middle of calling `.index()` and `.save()` .

```
Traceback (most recent call last):
  File "C:\Python\lib\weakref.py", line 648, in _exitfunc
    f()
  File "C:\Python\lib\weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Python\lib\tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "C:\Python\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\LUISAR~1\\AppData\\Local\\Temp\\tmphx03gy2g\\documents'
```

To answer your question, my object is created `Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2", "content": True, "objects": True})` so it is a yes. I'm also running `Python 3.7.9`.

Thanks!

**Comment by davidmezzetti** [comment]
Would you mind trying this on Python 3.8? This fix while old wasn't backported to 3.7 - https://github.com/python/cpython/issues/70847

Ultimately, I could implement the same logic in the archiving logic to work around Windows permission errors but I'm curious if it's still an issue with later version of Python.

**Comment by luisArandas** [comment]
I found a solution, lol. Just saving uncompressed format in Windows and compressed in MacOS, it seems to go away and work fine. If I don't specify the tar file and just a folder, it seems to be working properly

**Comment by davidmezzetti** [comment]
That makes sense given the issue. When archiving is enabled, files are written to a temporary directory then saved to a compressed file. When the temporary directory goes out of scope, finalization logic in Python tries to delete the directory and this is where the error is coming on Windows.

Looking at the CPython code, there is additional logic in Python 3.8 that's not in Python 3.7....so definitely possible the fix mentioned above resolved the issue. The "fix" though isn't anything more than ignoring the error, so that option is certainly one txtai could integrate.

**Comment by davidmezzetti** [comment]
Given that this is a Python 3.7 specific error, the best path is to upgrade to a later Python version if this error is occurring frequently. Python 3.9+ is best when using Windows.
