### ISSUE TITLE
Colab example not working

### ISSUE THREAD

**Issue by Clemens123** [neuml/txtai#268]
Hi, I tried your notebook at https://colab.research.google.com/github/neuml/txtai/blob/master/examples/10_Extract_text_from_documents.ipynb
but the second cell ("Create a Textractor instance") returns an error:
`RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'PIL.Image' has no attribute 'Resampling'`
Do you have any idea how to fix this?
Great project though!

**Comment by davidmezzetti** [comment]
Thank you for giving txtai a try!

This is similar to these issues: https://github.com/neuml/txtai/issues/255 and https://github.com/neuml/txtai/issues/257

In certain cases, Colab requires a restart when updating libraries. Unfortunately, I haven't found a clean automated way to do this outside the runtime restart and re-run pattern.

**Comment by Clemens123** [comment]
Great, I had no idea a restart could help :)
