### ISSUE TITLE
Word Embedding Question

### ISSUE THREAD

**Issue by avimeens** [neuml/txtai#27]
I am trying to run the Example 1 with word embeddings using the following code:
embeddings = Embeddings({"path": "word-vectors/GoogleNews-vectors-negative300.magnitude",
            "storevectors": True,
            "scoring": "bm25",
            "pca": 3,
            "quantize": True})

sections = ["US tops 5 million confirmed virus cases",
            "Canada's last fully intact ice shelf has suddenly collapsed, forming a Manhattan-sized iceberg",
            "Beijing mobilises invasion craft along coast as Taiwan tensions escalate",
            "The National Park Service warns against sacrificing slower friends in a bear attack",
            "Maine man wins $1M from $25 lottery ticket",
            "Make huge profits without work, earn up to $100,000 a day"]

print("%-20s %s" % ("Query", "Best Match"))
print("-" * 50)

for query in ("feel good story", "climate change", "health", "war", "wildlife", "asia", "north america", "dishonest junk"):
    # Get index of best section that best matches query
    candidates = embeddings.similarity(query, sections)
    uid = np.argmax(candidates)

    print("%-20s %s" % (query, sections[uid]))

But I am getting the following error:
-----------------------------------
Traceback (most recent call last):
  File "2.py", line 24, in <module>
    candidates = embeddings.similarity(query, sections)
  File "/home/vyasa/.virtualenvs/txtai/lib/python3.6/site-packages/txtai/embeddings.py", line 228, in similarity
    query = self.transform((None, query, None)).reshape(1, -1)
  File "/home/vyasa/.virtualenvs/txtai/lib/python3.6/site-packages/txtai/embeddings.py", line 179, in transform
    embedding = self.model.transform(document)
  File "/home/vyasa/.virtualenvs/txtai/lib/python3.6/site-packages/txtai/vectors.py", line 155, in transform
    weights = self.scoring.weights(document) if self.scoring else None
  File "/home/vyasa/.virtualenvs/txtai/lib/python3.6/site-packages/txtai/scoring.py", line 133, in weights
    weights.append(self.score(freq, idf, length))
  File "/home/vyasa/.virtualenvs/txtai/lib/python3.6/site-packages/txtai/scoring.py", line 217, in score
    k = self.k1 * ((1 - self.b) + self.b * length / self.avgdl)
ZeroDivisionError: float division by zero

Do I need to do something with the word embeddings before I can use it for similarity search ?

**Comment by davidmezzetti** [comment]
Thank you for taking the time to write an issue.

BM25 scoring requires a pass over the data before it can be used. If you add the following line before running the queries, it should work. With this demo dataset, it will pretty much be the same as average embeddings.

```python
embeddings.scores([(uid, text, None) for uid, text in enumerate(sections)])
```

**Comment by davidmezzetti** [comment]
Closing this issue, re-open if the issue still persists.
