### ISSUE TITLE
ImportError: Language detection is not available - install "pipeline" extra to enable

### ISSUE THREAD

**Issue by nleesalesloft** [neuml/txtai#270]
I'm using Google Colab and the exact tutorial from this github.

```
!pip install txtai[pipeline]
from txtai.pipeline import Translation
translate = Translation()
translation = translate("This is a test translation into Spanish", "es")
translation
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-63-2f6e604dabe6>](https://localhost:8080/#) in <module>()
      1 # Create translation model
      2 translate = Translation()
----> 3 translation = translate("This is a test translation into Spanish", "es")
      4 translation

1 frames
[/usr/local/lib/python3.7/dist-packages/txtai/pipeline/text/translation.py](https://localhost:8080/#) in detect(self, texts)
    115 
    116         if not FASTTEXT:
--> 117             raise ImportError('Language detection is not available - install "pipeline" extra to enable')
    118 
    119         if not self.detector:

ImportError: Language detection is not available - install "pipeline" extra to enable

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by davidmezzetti** [comment]
Thank you for giving txtai a try!

This is similar to these issues: https://github.com/neuml/txtai/issues/255, https://github.com/neuml/txtai/issues/257 and https://github.com/neuml/txtai/issues/268

In certain cases, Colab requires a restart when updating libraries. Unfortunately, I haven't found a clean automated way to do this outside the runtime restart and re-run pattern.
