### ISSUE TITLE
from txtai.pipeline import Translation

### ISSUE THREAD

**Issue by twinkle055** [neuml/txtai#279]
Failed to import transformers.pipelines because of the following error (look up to see its traceback):
module 'PIL.Image' has no attribute 'Resampling'
Package not working
![image](https://user-images.githubusercontent.com/57221810/168471029-a499e6d6-8841-4a19-a03c-7d7a6d6a91e4.png)

Check code here(Not working): https://github.com/neuml/txtai/blob/master/examples/12_Translate_text_between_languages.ipynb

**Comment by davidmezzetti** [comment]
Thank you for giving txtai a try!

This is similar to these issues: https://github.com/neuml/txtai/issues/255, https://github.com/neuml/txtai/issues/257 and https://github.com/neuml/txtai/issues/268

In certain cases, Colab requires a restart when updating libraries. Unfortunately, I haven't found a clean automated way to do this outside the runtime restart and re-run pattern.

**Comment by davidmezzetti** [comment]
Closing this issue. Feel free to reach back out with further questions.
