### ISSUE TITLE
deploying API with docker on AWS

### ISSUE THREAD

**Issue by luquitared** [neuml/txtai#284]
Hello,

I am currently attempting to run this dockerfile on an EC2 instance on amazon AWS. The instance being used has a lot of CPU and RAM.

``` dockerfile
FROM neuml/txtai-cpu

# Copy configuration
COPY config.yml .

RUN python -c "from txtai.api import API; API('config.yml', False)"

# Start server and listen on all interfaces
ENV CONFIG "config.yml"
ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "--port", "80", "txtai.api:app"]

EXPOSE 80
```

I have to use `EXPOSE 80` because I using amazon EBS.

When reading the logs, I can see the app is running:
``` bash
INFO:     Application startup complete.

2022-05-26 06:36:46,997 [INFO] startup: Application startup complete.

INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)

2022-05-26 06:36:47,001 [INFO] _log_started_message: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
```

When I try to access the service at localhost:80/docs or localhost:8000/docs I receive this error:
```
No supported WebSocket library detected. Please use 'pip install uvicorn[standard]', or install 'websockets' or 'wsproto' manually.
```

I don't know how to view the original txtai-cpu image, otherwise, I'd try to modify that logic. Am I making a mistake or is this something related to the dockerfile?

**Comment by davidmezzetti** [comment]
Hi @luquitared 

I'm not able to reproduce this issue locally with Docker. To make sure I understand, you're running this on AWS or locally? If it's on AWS, I'm not following how the connection works with localhost. 

What happens if you run your code locally with Docker? Something like:

```
docker build .
docker run -p 80:8000 <image id>
```

Alternatively, what if you add this to your DockerFile:

```
RUN python -m pip install --no-cache-dir uvicorn[standard]
```

**Comment by luquitared** [comment]
If I run that locally, it works perfectly.

I think the issue is that I don't know how to pass docker flags to the amazon ebs instance. For example, using:
`docker run -p 80:8000` works perfectly locally, but If I don't use that to run it, it does not work locally.

**Comment by luquitared** [comment]
Perhaps I'll make a docker-compose file so I can expose both host and container

**Comment by luquitared** [comment]
Ope. No, your suggestion worked. Ran it with
`RUN python -m pip install --no-cache-dir uvicorn[standard]` & worked!

**Comment by davidmezzetti** [comment]
Sounds good, glad you were able to get it to work!
