### ISSUE TITLE
Unexpected behavior from .index() method

### ISSUE THREAD

**Issue by luquitared** [neuml/txtai#286]
Hey David. I hope I am not posting here too much. I am almost done with my entire application, can't wait to show you.

Basically, I have a dict object "documents" that looks like this:
```
{ 
'filename': str
'chunks': [str]
}
```

After, I pass a list of these documents dictionaries to this method:
``` python
    def custom_index(self, documents: List[Dict]):

        uid = 0
        
        for i, doc in enumerate(documents):
            for chunk in doc['chunks']:
                embeddings.index([(uid, {"URL": doc["filename"], "text": chunk}, None)])
                print(uid)
                uid += 1
        
        embeddings.save(self.index_name)

        return True
```

The reason I am doing this is that the document dictionary represents a single website. The "chunks" are pre-processed text and are pieces of the website's content. This way I can search for specific sections of a website, but when I get back a "chunk" I can see what URL it belongs to.

 The issue I am facing is that after running this method, it appears there is only one element that exists in the index. It seems that with each loop, it is erasing the existing index and replacing it with a single object every time.

**Comment by luquitared** [comment]
It looks like I have to build the entire list before I can run .index():
``` python
[(uid, {"URL": doc["filename"], "text": chunk}, None)]
```

**Comment by davidmezzetti** [comment]
No problem with the posts at all, happy to see you moving forward.

Regarding index, the behavior you are seeing is expected. The [index](https://neuml.github.io/txtai/embeddings/methods/#txtai.embeddings.base.Embeddings.index) method is designed to be run once per index and it will overwrite the existing index.

If you want to make multiple updates, the [upsert](https://neuml.github.io/txtai/embeddings/methods/#txtai.embeddings.base.Embeddings.upsert) method is designed for that. If you switch your code above as follows, things should work:

```python
    def custom_index(self, documents: List[Dict]):

        uid = 0
        
        for i, doc in enumerate(documents):
            for chunk in doc['chunks']:
                embeddings.upsert([(uid, {"URL": doc["filename"], "text": chunk}, None)])
                print(uid)
                uid += 1
        
        embeddings.save(self.index_name)

        return True
```

**Comment by luquitared** [comment]
Amazing! Typing this out helped me think it through also and just created this which also worked:
``` python
    def custom_index(self, documents: List[Dict]):
        uid = 0
        index_list = []
        for i, doc in enumerate(documents):
            for chunk in doc['chunks']:
                index_list.append((uid, {"URL": doc["filename"], "text": chunk}, None))
                print(uid)
                uid += 1
        embeddings.index(index_list)
        embeddings.save(self.index_name)
        return True
```

I'll stick with the upsert, seems more elegant
