### ISSUE TITLE
Similarity search and filtering documents by user_id inside SQL

### ISSUE THREAD

**Issue by luquitared** [neuml/txtai#301]
Hi David,

I currently have an index with documents that are owned by different users. I want the users to be able to search their documents but to only see the documents that match their user_id. 

When I run this SQL query:
``` SQL
select * from txtai where user_id = 0
```

I am returned this object:
``` JSON
[
	{
		"indexid": 5007,
		"id": "0",
		"text": "This is a test",
		"tags": null,
		"entry": "2022-07-01 18:38:45.665031",
		"data": "{\"text\": \"This is a test\", \"user_id\": 0}",
		"object": null,
		"score": null
	}
]
```

However when I try this query:
``` SQL
select * from txtai where similar('this is test') and user_id = 0
```

I am returned an empty array. Is this the way it is supposed to work? Thanks again :)

**Comment by davidmezzetti** [comment]
Hi @luquitared - This can happen sometimes when the candidate list is too short. The code tries to pick a sensible default based on the database size but it can also be set in the query. 

What if you run this:

```sql
select * from txtai where similar('this is test', 500) and user_id = 0
```

Is the text in your database all the same or was the text "This is a test" just a notional example.

**Comment by luquitared** [comment]
No results still.

Something to note - all other objects in the index do not have user_id. Not sure if this impacts the query. I plan to re-do the entire index with this attribute though.

**Comment by luquitared** [comment]
Once I added a bunch of documents this problem has disappeared!

**Comment by davidmezzetti** [comment]
Glad to hear it's all working now!
