### ISSUE TITLE
A nicer way to share your Colab Tutorials/Documentation 

### ISSUE THREAD

**Issue by ColabDog** [neuml/txtai#302]
Hi,

I'm enjoying the documentation of txtai! I found your progress to be astounding as a 1 man team! (I think?)
Nevertheless, I am the creator of ColabDog here and I wanted to share a useful extension. I found your package to be really interesting but I found that constantly switching between your Colab documentation to be quite difficult and I understand that as a data scientist, we just want to quickly test out new things. Over my weekends, I developed a Chrome extension that allows users to be able to flick between your useful Colabs. I was wondering if you would find something like this useful? I would love to get feedback on this! 

Below is a screenshot. On the right - you can see a list of directories to all the different Colab Notebooks you have. 

![image](https://user-images.githubusercontent.com/108557828/177171848-21746a28-ab5a-4f1a-9c8a-2f65c4a37316.png)

You can install the Chrome Extension [here](https://github.com/ColabDog/colabdog-chrome-extension-releases/releases). 
And once you install the Chrome extension, you can simply click on the link below to see the Playlist!

[Colab Playlist](https://colab.research.google.com/github/neuml/txtai/blob/master/examples/01_Introducing_txtai.ipynb?colabDogPlaylist=%5B%28%27tXle%21%27U+J+%E2%96%B6%EF%B8%8F6*01_U_J8wXh+Huggkg+Face+DTasets6*02KwXh_Huggkg_Face_DTasets8fromOdTa+source6*03Kfrom_a_dTa_source-Add+z+G+to+ElaqicG6*04_Add_z_G_to_ElaqicG-j+G+wXh+images6*13_j_G_wXh_images-V+e7+cluqer6*15_V_e7_cluqer-WhT%22s+new+k+J+4.06*24_WhTs_new_k_J_4_0-AnTomy+ofOJ+R6*29_AnTomy_of_a_J_R-Cuqom+E7+SQL+Z6*30_E7_SQL_cuqom_Z-Model+N6*32_Model_N-Query+Y6*33_Query_Y-POQA+dTabase6*34_P_a_QA_dTabasev%5D*ps%3A%2F%2FgXhub.com%2Fneuml%2FJ%2Fblob%2Fmaqer%2Fexamples%2F-v%2C%28%27tXle%21%276%27%7Eurl%21%27htt7mbeddkgs8-P+an+E7+R+GsearchJtxtaiK_P_an_E7_R_NexplakabilXyO+a+PBuildRkdexTatUIntroduckgVDiqributedXitYtranslTionZfunctionsjSimilarXykinqstv.ipynb%27%29zsemantic%01zvqkjZYXVUTRPONKJG876-*_)

Below is a GIF of the improved user experience with your Colab documentation! 👍 

![txtai](https://user-images.githubusercontent.com/108557828/177174233-44ca72ed-ae0a-4017-9cdf-5f4bf46fd135.gif)

I'm keeping tabs on this thread, but feel free to email me at colabdog@gmail.com if you would like to further discuss/ask questions.

**Comment by davidmezzetti** [comment]
Thank you for sharing and the kind words! 

I don't typically install Chrome extensions for a number of reasons but I'm happy to keep an eye on this as it develops. This issue will continue to be discoverable should anyone want to navigate this way.
