### ISSUE TITLE
ambiguous behavior of limit parameter in sql query search 

### ISSUE THREAD

**Issue by a-bawane** [neuml/txtai#307]
According to my understanding, limit parameter => maximum number of results to be displayed
But in sql query serach, when limit is kept 100 then results are displayed (20+ results) whereas if limit =10 no results display.
If results are present (20+) for that query then txtai should return 10 results when limit =10.

The limit parameter works as expected in text search (no sql query).

Request Body for /batchserach
{
  "queries": [
    "SELECT id, filename, text, score from txtai WHERE similar(' TOXICITY OF HEXANEDIOIC ACID DILITHIUM SALT ') AND project='test'"
  ],
  "limit": 10
}

**Comment by davidmezzetti** [comment]
Depending on your data distribution and filters used, you may need to increase the candidate list for the similar clause. 

For example:

```sql
SELECT id, filename, text, score from txtai WHERE similar(query, 500) AND project='test'
```

More can be read on this here: https://neuml.github.io/txtai/embeddings/query/#similar-clause

**Comment by a-bawane** [comment]
Thanks, It helped. 

**For reference** :-
similar("query", "number of candidates")
The txtai query layer has to join results from two separate components, a relational store and a similarity index. With a similar clause, a similarity search is run and those ids are fed to the underlying database query.

The number of candidates should be larger than the desired number of results as additional filtering could occur. If this is not specified, it defaults to 10 times the number of desired results.
