### ISSUE TITLE
Textractor not identifying pdf format with Tika running

### ISSUE THREAD

**Issue by YuriWerewolf** [neuml/txtai#315]
I am running Apache Tika server, when running code below (from the examples) looks like Textractor thinks input is a website rather than pdf file.
It cannot find local file so I have to use  'file://localhost//' +  for it to find it.
Then the result is below:

```
textractor = Textractor(sentences=True)
textractor(filepath)
```

2022-07-27 18:02:14,574 [WARNING] __init__: Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
['%PDF-1.7 %���� 1 0 obj <>/Metadata 199 0 R/ViewerPreferences 200 0 R>> endobj 2 0 obj <> endobj 3 0 obj <>/ExtGState<>/XObject<>/ProcSet[/PDF/Text/ImageB/ImageC/ImageI] >>/Annots[ 17 0 R] /MediaBox[ 0 0 612 792] /Contents 4 0 R/Group<>/Tabs/S/StructParents 0>> endobj 4 0 obj <> stream x��][��ȱ~7���� H����f�r` �o�8�"�����\x03��,�\x1aiBqv����S_u�"�=��%/� ��X����u��\x17M[��e;{���Eۖ�uu3������ ��?�U�?� �m�ֻ���\x0f-.��*o���j����ٿ�>��\x18

when using tika itself:

```
import tika
from tika import parser
parsed = parser.from_file(filepath)
print(parsed["metadata"])
print(parsed["content"])
```

I get the correct values:
{'Author': 'Ban Yan', 'Content-Type': 'application/pdf', 'Creation-Date': '2022-05-02T13:......

Why does Textractor not realize it is a pdf file and uses appropriate method?

**Comment by davidmezzetti** [comment]
Thank you for reporting the issue.

It seems like the checkjava method doesn't think Java is installed and falls back to use BeautifulSoup. What happens if you run

```python
textractor.checkjava()
```

Does that return true or false? Are you running Tika on a different host via TIKA_SERVER_ENDPOINT?

**Comment by YuriWerewolf** [comment]
Looks like it sees java installed and after PC restart everything works

![image](https://user-images.githubusercontent.com/18197357/181452171-7dae58e6-eb16-4405-8261-da3de53641ae.png)

I have also enclosed Java path in "" in JAVA_PATH, may be that helped.
Works today, thanks.

**Comment by davidmezzetti** [comment]
Glad to hear it, feel free to respond back here if the error resurfaces.
