### ISSUE TITLE
Is Embeddings.search() support GPU?

### ISSUE THREAD

**Issue by muazhari** [neuml/txtai#316]
Is Embeddings.search() support GPU? If it is supported, how to use the GPU support?
If it is not supported, do I need to revise codes from
https://github.com/neuml/txtai/blob/3ced24d7e3ee926e4ef58ed510a1edc3ade2bca8/src/python/txtai/ann/faiss.py#L26
to
```python
self.model = faiss.index_cpu_to_all_gpus(index_factory(embeddings.shape[1], params, METRIC_INNER_PRODUCT))
```
?

References
- https://github.com/facebookresearch/faiss/wiki/Running-on-GPUs

**Comment by davidmezzetti** [comment]
Yes, something like this would enable GPU ops. The [faiss-gpu](https://pypi.org/project/faiss-gpu/) package would also need to be installed. A flag could be added to ann/faiss.py to enable moving the models from/to GPUs.

Adding GPU support for Faiss hasn't been a high priority as the vast majority of indexing time comes from the vectorization process.

**Comment by davidmezzetti** [comment]
Closing this as completed. If there are further questions please feel free to re-open or open a new issue.
