### ISSUE TITLE
[Que] is it possible to search on tags which are added with text?

### ISSUE THREAD

**Issue by a-bawane** [neuml/txtai#317]
As per my understanding, embeddings are only built on text and we can do search on them; while meta tags can be used to filtering out the results.
I want to do search on text as well as meta tags (stored in data field), so can we build embeddings on tags and configure txtai to do search on meta tags as well?

My requirement is both text as well tags should be considered while searching.  Is this possible with txtai or any other way to achieve this?

**Comment by davidmezzetti** [comment]
As long as content storage is enabled, you can search tags as part of a SQL query.

For example:

```sql
select id, text, score from txtai where similar('text') and tags like '%tag%'
```

Additional metadata can also be added to records at index time.

```python
record = {"text": "text to index", "flags": {"f1": 1, "f2": 1, "f3": 1}}

# Build embeddings and index with record
embeddings = Embeddings(...)
embeddings.index([(0, record, tags)])
```

```sql
select id, text, score from txtai where similar('text') and flags.f1
```

**Comment by davidmezzetti** [comment]
Another thing that trips people up is the similar candidate list when using filters. If you don't get the results you expect, try changing the candidate parameter - https://neuml.github.io/txtai/embeddings/query/#similar-clause

**Comment by a-bawane** [comment]
Thanks for the reply.
I already using SQL query for filtering out the result using tags. I wanted to use search on tags like we do search on text, so that score will also get affected. If tags/keywords mentioned in search query then, it will have higher score.

**Comment by davidmezzetti** [comment]
Unfortunately, only a single text similarity field is supported per index for similarity queries. This has also been discussed in #288 and it's on the roadmap to allow multiple similarity fields per index.

Couple options to consider as of now:

1. Make the text field text + keywords. You could have a format like "[tags] text". 
2. [Add a custom score function](https://neuml.github.io/txtai/embeddings/query/#custom-sql-functions) that takes (score, query, tags) and builds a custom score. For example:
    ```python
    def tscore(score, query, tags):
        return score + 0.25 if tags and query in tags else score 

    embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2",
                             "content": True, "functions": [tscore]})

    embeddings.index([(0, "text", None), (1, "text", "tag1")])

    embeddings.search("select id, text, tscore(score, 'tag1', tags) score from txtai where similar('text')")
    ```

    Note that this only scores after results have already been obtained from the ANN index.

**Comment by a-bawane** [comment]
good to know it's on the roadmap to allow multiple similarity fields per index.
