### ISSUE TITLE
How to attach custom text IDs to texts argument in Similarity feature?

### ISSUE THREAD

**Issue by muazhari** [neuml/txtai#321]
I need features like in the [Embeddings](https://neuml.github.io/txtai/embeddings/methods/#txtai.embeddings.base.Embeddings)   feature to be able to attach custom IDs to the supplied texts data to the embedding index in the [Similarity](https://neuml.github.io/txtai/pipeline/text/similarity/) feature. Meanwhile, based on what I currently know, the [Similarity](https://neuml.github.io/txtai/pipeline/text/similarity/) feature can't have the ability to attach custom IDs to the supplied text argument. If these custom ID things in [Similarity](https://neuml.github.io/txtai/pipeline/text/similarity/) texts arguments are currently not supported, Is there any workaround?

**Comment by davidmezzetti** [comment]
The Similarity pipeline returns a list of (id, score) tuples where id is the position in the input data array. The best thing to do would be to have a list of records having whatever content you want to compare. For example, the code below has an array of dictionaries with ids and text elements. Just the text is run through the similarity pipeline and then the first id is used to retrieve the full row.

```python
from txtai.pipeline import Similarity

rows = [{"id": "id1", "text": "text1"}, {"id": "id2", "text": "text2"}]

similarity = Similarity()
results = similarity("query", [row["text"] for row in rows])
print(rows[results[0][0]])
```

**Comment by davidmezzetti** [comment]
Closing this as completed. If there are further questions please feel free to re-open or open a new issue.
