### ISSUE TITLE
Multiarch docker image

### ISSUE THREAD

**Issue by hkad98** [neuml/txtai#324]
Could you please, consider making a neuml/txtai-cpu multiarch docker image supporting ARM CPUs? 
Unfortunately, for users with Apple Silicon CPUs, docker images that do not support ARM can result in several issues, such as performance.

**Comment by davidmezzetti** [comment]
Thank you for submitting this. I'll take a look at creating an image supporting ARM CPUs.

**Comment by hkad98** [comment]
@davidmezzetti, thank you!

**Comment by davidmezzetti** [comment]
There is now an ARM64 build on Docker Hub - https://hub.docker.com/r/neuml/txtai-cpu/tags

Moving forward the default build will be a multiarch image for amd64/arm64. But I didn't want to update the current v5.0.0 image.
