### ISSUE TITLE
Serverless vector search - failed to call webhook

### ISSUE THREAD

**Issue by edanweis** [neuml/txtai#329]
i'm trying to follow your tutorial on Medium. 

https://medium.com/towards-data-science/serverless-vector-search-with-txtai-96f6163ab972

But, I'm getting an error on Step 6.

```
Error: Internal error occurred: failed calling webhook "webhook.serving.knative.dev": failed to call webhook: Post "https://webhook.knative-serving.svc:443/defaulting?timeout=10s": dial tcp 10.96.113.11:443: connect: connection refused
```

Any ideas? Thanks

**Comment by davidmezzetti** [comment]
Sorry to hear you're running into issues. Happy to help. 

Perhaps there is something in the output of the previous steps that didn't outright fail but didn't install correctly. The first place I'd look is the output of this command. 

```
$ kind get clusters
kind
knative
```

The error leads me to believe Knative isn't available in the cluster.

**Comment by edanweis** [comment]
Thanks David, the error is gone, must have been something else, perhaps a reboot.

I'm hoping to use an image search/embedding workflow (similar to the streamlit example) but with the serverless setup. Is that possible?

**Comment by davidmezzetti** [comment]
Glad to hear it's working now.

Image search should work the same, it's just a different model that encodes the data but otherwise everything is the same.
