### ISSUE TITLE
Feature: Improve performance of Translation with different underlying library

### ISSUE THREAD

**Issue by nickchomey** [neuml/txtai#354]
I see that txtai uses Helsinki OPUS MT models for translation, but it is rather slow for me. I suspect this has at least something to do with Python. 

As with using Tika server rather than Python-based text extraction packages, I wonder if there's a way to make use of the OPUS models with the Marian Server in order to take advantage of C++'s considerable speed advantage?

I'm not knowledgeable enough to investigate further, but here's some reference materials that might be useful:
https://stackoverflow.com/questions/65541788/how-to-reduce-the-inference-time-of-helsinki-nlp-opus-mt-es-en-translation-mode
https://huggingface.co/docs/transformers/model_doc/marian
https://github.com/Helsinki-NLP/OPUS-MT#installation-of-the-tornado-based-web-app
https://github.com/Helsinki-NLP/OPUS-MT-train
https://github.com/DFKI-NLP/marian-docker
https://hub.docker.com/r/intel/nmt_marian_framework_demo

**Comment by davidmezzetti** [comment]
This seems like a good idea suited for a workflow. The workflow could call a translate function hosted via an API. 

Regarding speed are you running the translations on a CPU-only system?

**Comment by davidmezzetti** [comment]
It would take some profiling but the slow performance probably is more model based than pre/post processing. The tokenizers package is written in Rust which will run at native speed. The models run in PyTorch is which is C/C++ then CUDA/GPU. It's possible that the translate pipeline has poorly performing code that could be slowing things down too. Ultimately as the links above allude, it could be that the Marian framework is just more highly tuned for these models and faster. 

An example notebook that spins up a Marian server and runs a translation workflow would be an interesting add as it would further demonstrate how workflows can call external services.

**Comment by davidmezzetti** [comment]
Thank you for the detailed notes here. I'd prefer to stay close to the Hugging Face ecosystem for this component. It's actually quite popular, perhaps the most popular component in txtai.

It appears that these approaches all require 3rd party libraries and have their own systems for managing models etc. If you'd like to have a CTranslate2 pipeline for txtai workflows, a custom pipeline would be straightforward to implement. Something like this:

```python
from txtai.pipeline import Pipeline

class CTranslate2(Pipeline):
  def __init__(self, path):
    translator = ctranslate2.Translator(path)

  def __call__(self, inputs):
    translator.translate_batch(inputs)
```

**Comment by davidmezzetti** [comment]
Going to close this one out in favor of a custom pipeline for CTranslate2
