### ISSUE TITLE
Allow for setting custom translation model path

### ISSUE THREAD

**Issue by nickchomey** [neuml/txtai#355]
Right now, we cannot set/use a custom path for the Translation pipeline. The path set in the parameter is only used as a default fallback in the event that the language pair doesn't have a Helsinki OPUS model available. 

Moreover, even if we change the path, the `load()` method defaults to using the `M2M100 `class from `transformers`

So, there's no possibility of using mT5, for example. Or, for that matter, it is impossible to use M2M unless you are using an obscure language pair. 

Related, is it possible to use `facebook/m2m100_1.2B`? Or can we only use the 418M version?

**Comment by davidmezzetti** [comment]
You should be able to pass `facebook/m2m100_1.2B` as a path parameter to the translate pipeline.

There could be a change that forces all translation to run through the model specified on path and disables language/model detection. Would that be helpful?

**Comment by davidmezzetti** [comment]
This pipeline has been updated to have broader model support. There is also a new option, `findmodels` which can be set to false. When false, the pipeline will always use the base model for translations.

I was able to locally run translations with `m2m_100`, `marian`, `mbart`, `nllb` and `t5` models. I'll update the translation notebook with examples.
