### ISSUE TITLE
Example 31 - Duplicate image detection not working

### ISSUE THREAD

**Issue by nickchomey** [neuml/txtai#357]
I get this when I run the colab
![image](https://user-images.githubusercontent.com/88559987/194916431-0715033e-d0e6-42a9-8f0e-74fc98c0e96b.png)

and this when i run it in vscode jupyter

![image](https://user-images.githubusercontent.com/88559987/194916479-99caaecb-1a48-4f88-bd9f-ed50403246c0.png)

The code seems logically fine to me, so perhaps something has broken with ImageHash or textdistance?

**Comment by davidmezzetti** [comment]
Thank you for reporting this, it's been fixed and the notebook updated.
