### ISSUE TITLE
What tool do you use to generate your diagrams?

### ISSUE THREAD

**Issue by aknooh** [neuml/txtai#384]
David,
I really like the documentation for txtai. It is very clear, very well detailed, and easy to understand. You also have some of the nicest and cleanest diagrams out there like [flow.png Diagram](https://raw.githubusercontent.com/neuml/txtai/master/docs/images/flows.png#gh-light-mode-only) and [why.png Diagram](https://raw.githubusercontent.com/neuml/txtai/master/docs/images/why.png#gh-light-mode-only). 

Thank you for taking the time and effort and creating such nice diagrams.
If I may ask, what tool(s) did you use to create these diagram? Do you mind sharing please? Would love to know.

**Comment by davidmezzetti** [comment]
Thanks for the kind words!

The documentation site uses [https://excalidraw.com/](https://excalidraw.com/) to generate the images. It's all web based. The [originals are in GitHub](https://github.com/neuml/txtai/tree/master/docs/images) and can be loaded using that site.

**Comment by aknooh** [comment]
Awesome. Thank you very much!
