### ISSUE TITLE
Store and query by data when `content: False`

### ISSUE THREAD

**Issue by LoopControl** [neuml/txtai#385]
I am trying to index a few million images totaling a few Terabytes in size for a similarity search.

When I set Embeddings' `content` to `True`, I am able to store and query data with each image record (user_id and a few other fields to filter the similarity search by):
```
embeddings = Embeddings({"batch": 2, "encodebatch": 2, "method": "sentence-transformers", "path": "sentence-transformers/clip-ViT-B-32", "content": True, "objects": "image" })
```

However, when I set `content: false` I only get the ID and score back and can no longer use SQL queries to query the data.

I believe this behavior is by design but is there any way to have the SQL store/query when content is set to false?

(The reason why `content: True` is not a good option for me is because the images total in the Terabytes and I don't wish to duplicate that much data)

Thanks for creating the library, it definitely makes working with these models much easier.

**Comment by davidmezzetti** [comment]
Thanks for kind words.

Content storage can be enabled without storing objects. If the `objects` config param is omitted, the images will still be indexed just not stored. In this scenario, all fields _except_ objects will be stored in the database and available for querying/retrieval. 

For example:

```python
# Create embeddings
embeddings = Embeddings({
  "batch": 2,
  "encodebatch": 2,
  "method": "sentence-transformers",
  "path": "sentence-transformers/clip-ViT-B-32",
  "content": True 
})

# Index data
embeddings.index([(0, {"object": Image.open(..), "field1": "value", "field2": "value"}, None)])

# Run search
embeddings.search("select id, object, score from txtai where similar('query') and field1 = 'value'")
```

The query above will return a row with the id and score but object will be empty. The id can then be used to retrieve the image in the external data store. 

Hope this helps.

**Comment by LoopControl** [comment]
That worked perfectly! Thank you!

Now off to start a multi-day job to index a few million images..
