### ISSUE TITLE
Allow searching by embedding

### ISSUE THREAD

**Issue by lefnire** [neuml/txtai#396]
I'd like to search directly by an embedding I already have (not a string). Quick-fix is to check [here](https://github.com/neuml/txtai/blob/master/src/python/txtai/embeddings/search.py#L73) if the query is a string or nparray. If latter, skip the transform() step

**Comment by davidmezzetti** [comment]
Change is now in the main branch. Thanks for the idea, blending queries together is something I've never thought of.
