### ISSUE TITLE
Normalize BM25 and TF-IDF scores

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#401]
BM25 and TF-IDF scores are unbounded. They will continue to grow as the match improves. This change adds a flag to normalize scores from 0 - 1.

This method will calculate an average score using the average document length, average frequency and average idf score. A max score will then be calculated as `4 * average score`. Lastly, scores will be scaled between 0 to 1 using the range of 0 to max score. 

Formulas for this shown below.

```python
average = score(average frequency, average idf, average document length)
max = 4 * average
score = score / max
```

**Comment by davidmezzetti** [comment]
It's just a value I found correlated well with dense vector scoring distributions.

**Comment by mustfkeskin** [comment]
BM25 scores retrieved from Elasticsearch can span widely different ranges, such as [7–10], [55–56], or [200–210]. In this context, using a threshold of 4 times the mean may introduce a skewed distribution, potentially biasing the interpretation toward the lower or higher end. Wouldn't this approach risk distorting the distribution

**Comment by davidmezzetti** [comment]
There is no good way to normalize a BM25 score this is the best idea I had at the time. You can choose to turn normalization off and use RRF.

**Comment by mustfkeskin** [comment]
Thank you for sharing the information.

I was planning to apply an additional scoring on top of Elasticsearch using a Painless script, but I was looking for a proper normalization method for BM25 scores. Since there doesn’t seem to be a standard way to normalize them properly, I’m considering excluding BM25-based values from the script.
