### ISSUE TITLE
Issue with upsert and graph 

### ISSUE THREAD

**Issue by akset2X** [neuml/txtai#421]
Something is wrong with upsert (I guess). I'm using txtai via API server with uvicorn. I'm facing issues when I do upsert, 

Issue is - Topics and Categories of my text embeddings getting deleted after upserting. But text, id and else things are remaining as usual.

**Steps to reproduce the issue:**
1. Configure the settings in a ".yml" file, and set path and graph topics & categories. (I am using the same config mentioned in semantic graphs example.)
2.  Create a list of sentences and index them one by one to txtai 
3. Search the embeddings using SQL query "select topic,text,category from txtai where id=1"
4.  Iam picking the sentence with id = 1, (you can pick anything, but /add and /upsert the same again)
5. Pick the sentence which has id=1 (or any one of the sentences that you have), and delete it and /add /upsert it again.
6. Now, Search using SQL query again "select topic,text,category from txtai where id=1"
7. Observe

For me, for the first time right after indexing , I could see the topics and categories for each text when I search with SQL query. But after upserting I am getting value as "null" for topics and categories for the text that I upsert.
It is working fine with index but not with upsert API.

Please refer the issue #394  to see the config I'm using.

**Comment by akset2X** [comment]
**Found a solution myself:**

I was doing upsert operarion of multiple data in a single shot using /add API by enclosing the " text , id " list , there I faced the above issue. 

That is, 
POST /add
[{id:1,text:"abc"},{id:1,text:"abc"},{id:1,text:"abc"},{id:1,text:"abc"},{id:1,text:"abc"}]
And then GET /upsert

Well, then I tried to split the list and fed them one by one, that trick worked without issues. I mean I tried by adding one by one using /add and /upsert APIs by calling them multiple times to make it work.

**Comment by akset2X** [comment]
I would like to ask another doubt, is there anyway to change the config, especially I want to modify the "categories" list that I have written in the config.yml. Everytime I have to reindex and save the embeddings to change the config file inside my index folder. It takes very long time.
Can I do that without reindexing ? Please provide the solution in API server approach, not as Python script, also the workflow idea is bit confusing for me.
It will be really helpful, if I get some idea on that.

**Comment by davidmezzetti** [comment]
I'll give this a try when I have time and report back.

**Comment by davidmezzetti** [comment]
The fix for this will be in shortly.

Regarding reindexing with the API, the only current way to do that is re-adding the data and re-running index.

It would be straight forward to add a reindex call to the API, if you create a separate issue, I'll take a look.
