### ISSUE TITLE
Modify translation pipeline langdetect parameter to accept language detection function

### ISSUE THREAD

**Issue by nickchomey** [neuml/txtai#423]
*See [this comment](https://github.com/neuml/txtai/issues/423#issuecomment-1426777995) for details on what to implement for this issue*

First and foremost, I've been getting errors while trying to install fasttext with a different package managers (pdm and poetry) and python versions (3.8-3.10). Looking at the issues in their repo, it seems that this is a [common issue](https://github.com/facebookresearch/fastText/issues/1298) for [many people](https://github.com/python-poetry/poetry/issues/6113).

Someone created [a simple pull request](https://github.com/facebookresearch/fastText/pull/1292) 6 months ago to fix this and it has been ignored - as have hundreds of other Issues and PRs. The project just seems to be abandoned.

But [Lingua](https://github.com/pemistahl/lingua-py) appears to be a new and very promising language detection tool. There is lots of Their benchmarks show increased accuracy, though they don't have any performance metrics for comparison. 

At the very least, could the fasttext dependency be switch to [this repo ](https://github.com/cfculhane/fastText) (the 6 month old bugfix PR)?

**Comment by davidmezzetti** [comment]
I came across this a few months back and was equally excited. But after investigating, the quality/speed wasn't great. While fasttext is difficult, that model works surprising well and fast. 

The bigger thing though was that it requires Python >= 3.8 while this project is >= 3.7. Python 3.7 is EOL this summer, so I would consider it again then.

I do think it would be beneficial to change the translation pipeline's langdetect parameter. If that parameter supported a callable, then someone could pass their own external language detection algorithm.

**Comment by davidmezzetti** [comment]
It shouldn't fail in that case because the dependency will be satisfied. Poetry uses pip, so it should have the same dependency logic where it only tries to install if the package isn't available. If you install it beforehand, it should skip the step of installing fasttext and hence you shouldn't get an error.

**Comment by davidmezzetti** [comment]
Currently, the langdetect parameter takes a path to a fasttext model. This should still be the default behavior but additional logic should be added in the `detect` method to support using an external function. A custom function would need to handle an iterable of text and return an iterable of detected languages.

The fasttext import error should only be thrown when trying to load a fasttext detector and it fails.

While implementation of external detectors **should not** be implemented, a couple ideas to test locally are:
- [Lingua](https://github.com/pemistahl/lingua-py) - Original library mentioned
- [xlm-v-base-language-id](https://huggingface.co/juliensimon/xlm-v-base-language-id)

There are also other Python-based libraries. 

For the tests, just use a dummy function that returns a language id, no need to import anything external.

**Comment by saucam** [comment]
@davidmezzetti let me try this one !

**Comment by davidmezzetti** [comment]
Sounds great, thank you!

**Comment by saucam** [comment]
@davidmezzetti I was wondering what language ids should be returned by the custom function. Do the language ids change based on the model used? If yes, then should we be mapping to the ids returned by fasttext model?

**Comment by davidmezzetti** [comment]
Fixed with #444
