### ISSUE TITLE
Pin onnxruntime for macOS in build script

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#425]
Pin onnxruntime==1.13.1 for macOS in build script due to following.

https://github.com/microsoft/onnxruntime/issues/14663

**Comment by babenek** [comment]
Workaround :( https://github.com/Samsung/CredSweeper/pull/265/files

**Comment by davidmezzetti** [comment]
Fixed with 9989eec95494816fbc83b78e3abf58120798b7f0
