### ISSUE TITLE
tokenizer.py

### ISSUE THREAD

**Issue by zhaogangthu** [neuml/txtai#43]
hi，

For English, it is a right tokenizer such as 
**tokens = [token.strip(string.punctuation) for token in text.lower().split()]**
and
**return [token for token in tokens if re.match(r"^\d\*[a-z][\-.0-9:_a-z]{1,}$", token) and token not in Tokenizer.STOP_WORDS]**
But for other language, for example Chinese, it makes wrong thing, so could you please revise this for different language, or give me some advice?

Thanks!

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue. Can you show how you are creating the Embeddings object? Are you using transformer or word backed vectors?

This is a good find with the default tokenizer. Another issue (#39) is most likely running into this same problem.

As a workaround, can you try passing in lists to the index/search/similarity calls. This will skip tokenization. 

In other words:

```python
embeddings.index([(uid, text.split(), None) for uid, text in enumerate(sections)])
embeddings.search(query.split())
```

or 

```python
embeddings.similarity(query, [x.split() for x in sections])
```

**Comment by zhaogangthu** [comment]
> Thank you for reporting this issue. Can you show how you are creating the Embeddings object? Are you using transformer or word backed vectors?
> 
> This is a good find with the default tokenizer. Another issue (#39) is most likely running into this same problem.
> 
> As a workaround, can you try passing in lists to the index/search/similarity calls. This will skip tokenization.
> 
> In other words:
> 
> ```python
> embeddings.index([(uid, text.split(), None) for uid, text in enumerate(sections)])
> embeddings.search(query.split())
> ```
> 
> or
> 
> ```python
> embeddings.similarity(query, [x.split() for x in sections])
> ```

Thank you for your reply. I sovled this problem by replace 
**return [token for token in tokens if re.match(r"^\d\*[a-z][-.0-9:_a-z]{1,}$", token) and token not in Tokenizer.STOP_WORDS]** 
with 
**return tokens**
Because it would return a [] if the string doesn't have any English letter (r"^\d\*[a-z][-.0-9:_a-z]{1,}$"). And for SentenceTransformer.encode(), it accept an input of strings， So in my case, I just transfer parameter of strings to SentenceTransformer.encode() which can solve this problem.

**Comment by davidmezzetti** [comment]
Thanks for the update. We'll keep this issue open and address it in the next release.

**Comment by davidmezzetti** [comment]
Issue should now be resolved. Tokenization can be disabled by setting the config option:

```python
Embeddings({"method": "transformers", path: "/path/to/model", "tokenize": False})
```
