### ISSUE TITLE
pass parameters to workflow using API in Docker

### ISSUE THREAD

**Issue by dominikstein-ibm** [neuml/txtai#436]
Hi David,

I'm using txtai Docker API image according to the documentation: [docker build -t txtai-api .](https://neuml.github.io/txtai/cloud/)
If I want to use the zero-shot classifier I have to provide the labels in the config.yml 

`# Zero-shot labeling
labels:
  path: MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7`

`# Workflow definitions
workflow:
    entity:
        tasks:
            - action: entity
              args: [null, "average", false, false]
    labels:
        tasks:
            - action: labels
              args: [["Addresse", "Klausel", "Deckungssumnme", "Postleitzahl", "Wohungsgröße", "Tarif", "Jahresprämie", "Versicherungslaufzeit", "Name", "Versicherungsbeginn", "AGB", "Ausnahmen", "Besondere Bedingungen"]]`

This means when I change labels, I always have to rebuild the Docker image. This goes against the main advantages of the zero shot classifier. I do have a UI where I could provide labels and provide them to txtai. Is there a way I can pass labels dynamically to the API without having to rebuild the Docker image everytime?
Thanks in advance

**Comment by davidmezzetti** [comment]
Perhaps using the `labels` API method would work? It takes both the text and labels are parameters.

An example of this is here: https://colab.research.google.com/github/neuml/txtai/blob/master/examples/08_API_Gallery.ipynb

**Comment by dominikstein-ibm** [comment]
Hi David, what would be the correct endpoint (URL) to call the API method?

<img width="455" alt="Bildschirm­foto 2023-02-21 um 15 50 59" src="https://user-images.githubusercontent.com/122356553/220378232-522049af-2459-470a-90b8-95dc99705919.png">

When calling the above mentioned endpoint it returns "not found". The same endpoint using "extract" is working fine

**Comment by davidmezzetti** [comment]
The end points are /label and /batchlabel

**Comment by dominikstein-ibm** [comment]
Thanks! That worked
