### ISSUE TITLE
Trouble loading local embeddings in custom dockerfile

### ISSUE THREAD

**Issue by jridevapp** [neuml/txtai#439]
Hey guys, 

 I am having an issue loading local embeddings in my custom docker image, as every time it runs it wants to download every time:
 
```
 embeddings = Embeddings(
    {"path": "all-MiniLM-L6-v2",  "content": True}) 
```
I have tried to set this path a number of different ways...I can see that it is pulling the HFvalidation error if the path is off. 

I am trying to get this set for serverless purposes. 

Do you have any tips here?

With thanks!

**Comment by davidmezzetti** [comment]
In your Docker file, you'll need something similar to this.

```dockerfile
RUN python -c "from transformers import AutoModel; AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')"
```

This will cache the model in the Docker image. 

As an FYI, more people are watching questions like this over on txtai's slack channel - https://join.slack.com/t/txtai/shared_invite/zt-1cagya4yf-DQeuZbd~aMwH5pckBU4vPg

**Comment by jridevapp** [comment]
Awesome thanks @davidmezzetti
