### ISSUE TITLE
Add support to install on aarch64

### ISSUE THREAD

**Issue by hsm207** [neuml/txtai#440]
If I run `pip install txtai==5.3.0` on a machine with the following properties:

> PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
> NAME="Debian GNU/Linux"
> VERSION_ID="11"
> VERSION="11 (bullseye)"
> VERSION_CODENAME=bullseye
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> 
> Linux b2fa2f31be6b 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux

the installation fails with this message:

```
Collecting txtai==5.3.0
  Using cached txtai-5.3.0-py3-none-any.whl (159 kB)
Collecting faiss-cpu>=1.7.1.post2
  Using cached faiss_cpu-1.7.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.9 MB)
Requirement already satisfied: numpy>=1.18.4 in ./.venv/lib/python3.11/site-packages (from txtai==5.3.0) (1.24.2)
Requirement already satisfied: pyyaml>=5.3 in ./.venv/lib/python3.11/site-packages (from txtai==5.3.0) (6.0)
ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from txtai) (from versions: none)
ERROR: No matching distribution found for torch>=1.6.0
```

Running the same command on this machine works:

> PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
> NAME="Debian GNU/Linux"
> VERSION_ID="11"
> VERSION="11 (bullseye)"
> VERSION_CODENAME=bullseye
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> 
> Linux e84bcfb0d0af 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:53:22 UTC 2022 x86_64 GNU/Linux

**Comment by davidmezzetti** [comment]
It looks like PyTorch doesn't have a package for Python 3.11 on PyPI (https://pypi.org/project/torch/#files). If you use Python <= 3.10 it should work. See this PyTorch issue for more - https://github.com/pytorch/pytorch/issues/86566

There is a Docker image for Linux/arm64 if that's helpful - https://hub.docker.com/r/neuml/txtai-cpu/tags

**Comment by hsm207** [comment]
thanks! downgrading to python 3.9 worked for me.
