### ISSUE TITLE
Problem with the workflow builder

### ISSUE THREAD

**Issue by jepeloa** [neuml/txtai#454]
When I use the Workflow builder I have a problem with the embeddings. I used first a text extraction with an url source and sentece splitter thats works fine, but when I try to add the embeddings an error appear: ValueError: too many values to unpack (expected 3). I tried using only the embeddings only and the same error appear. Perhaps a problem with streamlit version, but I upgraded to the last version (Version: 1.20.0) and the error still appear, 
Bellow an image of the error:
Thanks!
![issue](https://user-images.githubusercontent.com/13154341/225613808-8bd18505-64c1-4f3c-8b74-0a49d34e7a44.png).

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue. The workflow build has gotten quite stale over the last year and needs a couple refactors.

I'll update it and report back where when complete.

**Comment by davidmezzetti** [comment]
Please try the updated workflow builder, it's been refactored to use the latest txtai features.
