### ISSUE TITLE
Using external transform and similarity function reports an error ValueError: shapes (1,512) and (768,1) not aligned: 512 (dim 1) != 768 (dim 0)

### ISSUE THREAD

**Issue by jqsl2012** [neuml/txtai#460]
hi，can you help me

txtai version: 5.4.0
```
# use SentenceTransformer, return 768 dim
def transform(inputs):
    response = requests.get("http://127.0.0.1:8080/embedding/1?q=" + inputs[0])
    return np.array([response.json()['vec']], dtype=np.float32)
    
embeddings = Embeddings({"method": "external", "transform": transform})

npa = np.asarray([[x for x in range(768)]], dtype=np.float32)
embeddings.similarity('hello',npa)
```

ValueError: shapes (1,512) and (768,1) not aligned: 512 (dim 1) != 768 (dim 0)

But if I don't use external, this error will not appear

**Comment by davidmezzetti** [comment]
It looks like the transform function returns vectors with 512 dimensions and the generated array `npa` creates 768 dimensions. 

What if you changed npa to this:

```python
npa = np.asarray([[x for x in range(512)]], dtype=np.float32)
```

**Comment by jqsl2012** [comment]
@davidmezzetti 
Thanks, was my problem, a vector of 768 dimensions was returned
