### ISSUE TITLE
Serious issue with : sentence-transformers/nli-mpnet-base-v2

### ISSUE THREAD

**Issue by VinayChaudhari1996** [neuml/txtai#471]
Previously It was working 

````
# %%capture

from txtai.embeddings import Embeddings

# Create embeddings model, backed by sentence-transformers & transformers
embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2"})


df["Tags"] = df["Tags"].str.lower()

tags_list = list(df["Tags"].values)

# Create embeddings index with content enabled. The default behavior is to only store indexed vectors.
embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2", "content": True, "objects": True})

# Create an index for the list of text
# embeddings.index([(uid, text, None) for uid, text in enumerate(tags_list)])

````

**Comment by xuzhimian** [comment]
I got the same issue, it seems like the model "sentence-transformers/nli-mpnet-base-v2" has been removed from huggingface.co repository.

**Comment by davidmezzetti** [comment]
Please see this related link: https://github.com/UKPLab/sentence-transformers/issues/1915

The Hugging Face Hub is currently having an issue but they know about it and are working on it. Will update once it's fixed.

**Comment by VinayChaudhari1996** [comment]
But how to fix this issue now in production? 
Anyone have quick fix , @davidmezzetti @hiway @xuzhimian

**Comment by davidmezzetti** [comment]
Assuming you have the models cached already, setting the OFFLINE_MODE flag might work around the issue. 

https://huggingface.co/docs/transformers/installation#offline-mode

**Comment by VinayChaudhari1996** [comment]
Sure @davidmezzetti 
Let me try that 
Thank you

**Comment by VinayChaudhari1996** [comment]
Hello Guys , 
Issue is fixed by HuggingFace team.

**Comment by davidmezzetti** [comment]
If you want more context regarding what happened, read this - https://twitter.com/huggingface/status/1656004153162756100
