### ISSUE TITLE
Similarity search not returning all results

### ISSUE THREAD

**Issue by dk-teknologisk-lcon** [neuml/txtai#472]
Really nice work on the repository, you have super useful functionalities and I think it's very intuitive to use, so thank you!

#### Description
I noticed when performing similarity search and setting a limit above/equal to the number of indexed documents, then often the number of results is less than the number of documents. The issue is also present if the search is performed as an SQL query with the similar() function (eg. "select text from txtai where similar('etc') limit 10000"). Is there another reason results would be excluded?

#### Details
Model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
txtai: 5.5.1
Python: 3.8.15
OS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.19045 Build 19045

#### Code to reproduce
```
from itertools import combinations

from txtai.embeddings import Embeddings

WORDS = ("a bunch of words that will be permuted in order to create documents for indexing").split()
docs = []
for i in range(2, len(WORDS) - 1):
	docs += [" ".join(x) for x in combinations(WORDS, i)]

embeddings = Embeddings({"path": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"})
embeddings.index([(uid, text, None) for uid, text in enumerate(docs)])

print("etc: ", len(embeddings.search("etc", 10000)), "results")
print("etc and so forth: ", len(embeddings.search("etc and so forth", 10000)), "results")

```
In my case my outputs were:

> etc:  1642 results

> etc and so forth:  1711 results

#### Notes
This doesn't seem to be related to a low score, as I have experimented with SQL queries on missing results. I have experienced it happening with short, medium, and long search strings. I have also experienced it in an embedding index with the content parameter set to true. This was actually the use case that lead to me encountering this, as I was trying to filter by a precomputed and stored field and sort by similarity, but not all documents were present.

Hugging face hub has a 404 error with sentence transformer models right now, but I first noticed the issue last week before that

**Comment by davidmezzetti** [comment]
Once the Hugging Face Hub is restored to normal operations, I'll take a look. Thanks for writing this up.

**Comment by davidmezzetti** [comment]
The default settings are designed to perform well in retrieving a typical batch of results for a search system. If you want to pull back 10,000 results per query, you have a couple options.

1. Set the faiss nprobe parameter higher
```python
embeddings = Embeddings({"path": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
"faiss": {"nprobe": 500}})
```

2. Use a different backend
```python
embeddings = Embeddings({"path": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
"backend": "hnsw"})
```

You can read more on ANN settings here - https://neuml.github.io/txtai/embeddings/configuration/#backend

**Comment by dk-teknologisk-lcon** [comment]
Fixed by setting nprobe higher 😄 Thanks very much!
