### ISSUE TITLE
make data - No such file or directory

### ISSUE THREAD

**Issue by belen-campos** [neuml/txtai#473]
Hi, i'm trying use this repo for the first time.

I used this [document](https://github.com/neuml/.github/blob/master/CONTRIBUTING.md) to set up my development environment, but i have an issue with the command : 
$ make data

I attach a screenshot of the error, i can't download https://github.com/neuml/txtai/releases/download/v3.5.0/tests.tar.gz

![Captura de pantalla 2023-05-09 a la(s) 17 50 59](https://github.com/neuml/txtai/assets/56655152/f55c48a1-7f7b-4def-8b8a-f7d8ead5ade3)

![Captura de pantalla 2023-05-09 a la(s) 17 47 46](https://github.com/neuml/txtai/assets/56655152/71dcad86-0888-479e-8df9-6624eba45993)

Should I change that download?

**Comment by davidmezzetti** [comment]
Is it possible that wget isn't installed? The tests URL is valid.

**Comment by belen-campos** [comment]
Hi, thank you, that was indeed it. Is there a way to modify the output of the error when running make data command?
Because the console error was:
"wget ​​command not found"
What is more intuitive than "No such file or directory"

**Comment by davidmezzetti** [comment]
A change was made to clarify this message.
