### ISSUE TITLE
Databases aside from SQlite

### ISSUE THREAD

**Issue by arvnoodle** [neuml/txtai#482]
I just checked this library today, had some good impression and might be one of the options my team can use in our current problem because we were just doing FAISS manually back then. can this be connected to other databases? I saw you can do SQL on txtai, so I can see doing some PostGreSQL. Would that be possible?

**Comment by davidmezzetti** [comment]
[DuckDB](https://duckdb.org/) is also supported. Additional databases can be added by extending the [Database](https://github.com/neuml/txtai/blob/master/src/python/txtai/database/base.py) class.
