### ISSUE TITLE
best to way to avoid db lock

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [neuml/txtai#487]
Excellent work on this! Currently I have a use case where I upsert and save the embedding index every 2 seconds with around 100 dcouments. It gives "sqlite3.OperationalError: database is locked" quite often when calling search whilst the index is updating/saving.  Whats the best way to tackle this?

currently my thought is to either:
* improve upsert performance somehow (upsert is not catching up with my input rate atm)
* have separate instances of Embedding and file (1 write 1 read) and copies txtai_writeonly to txt_readonly regularly but it might still fail during db lock 🤔

Any suggestion is appreciated

**Comment by davidmezzetti** [comment]
It depends on how you're handling concurrency. What is the current method being used to concurrently read and index?

**Comment by Vincent-liuwingsang** [comment]
thanks for the reply @davidmezzetti. no locks currently as the upserts operations can't catchup with input rate.
Prioritising read over update will still mean that the read might have to wait for the current upsert operation to finish(roughly 4-5 seconds average) which is something I want to solve for.

is there a way to speed up upsert or have a way to update the index in the background without affecting read(doesn't matter if the index is the most up-to-date)?

for context I'm using the following config for Embedding 
```{"path": "sentence-transformers/all-MiniLM-L6-v2", "content": "sqlite"}```

**Comment by davidmezzetti** [comment]
Are you loading the embeddings object each time you upsert or using an existing instance?  In other words, calling `embeddings.load` then `embeddings.upsert`. How many records are you running for each upsert?

**Comment by Vincent-liuwingsang** [comment]
currently I'm only calling `embeddings.load` once globally and all the subsequent upserts are called on that single instance.
```
103 records - 4.258456707000732 seconds (for embeddings.upsert)
107 records - 4.46355414390564 seconds
144 records - 5.727373838424683 seconds
144 records - 6.088770151138306 seconds
125 records - 5.261178255081177 seconds
```

**Comment by davidmezzetti** [comment]
Are you running on a CPU-only instance or one with at GPU. Those times seem consistent with how long vectorization would take with a CPU-only setup. Unless the text records are really large.

**Comment by Vincent-liuwingsang** [comment]
How do I check that?
I suspect its using CPU though as I'm on m1 mac and deviceId is returning -1 [here](https://github.com/neuml/txtai/blob/b30a96d9c2f4a9549377551599fff25018c6e6f0/src/python/txtai/vectors/transformers.py#L31-L32).

**Comment by Vincent-liuwingsang** [comment]
I've tried forcing `self.device = torch.device("mps")` [here](https://github.com/neuml/txtai/blob/b30a96d9c2f4a9549377551599fff25018c6e6f0/src/python/txtai/models/pooling.py#L35) but performance is similar to above

**Comment by davidmezzetti** [comment]
That makes sense. Does `torch.backends.mps.is_available()` return True?

If that returns true, you can try to force the model to load to the mps device with the code shown below.

```python
embeddings.model.model.to("mps")
```

**Comment by Vincent-liuwingsang** [comment]
it does return `True` and I tried your suggestion above but the performance still seem to be the same🤔

**Comment by Vincent-liuwingsang** [comment]
fairly short text as well where `select AVG(LENGTH(text)) from txtai` gives roughly 28

**Comment by davidmezzetti** [comment]
Certainly has uncovered that there should be a way to use the MPS device on a Mac M1, I'll create a separate issue for that.

I would try to run some of the examples in this thread - https://github.com/pytorch/pytorch/issues/77799 just to get a baseline of torch cpu vs mps on your machine.

**Comment by Vincent-liuwingsang** [comment]
sharing the benchmark where matrix multiplication of dimension 1000 is
cpu 2.8546828749822453
mps 4.164335416979156
where it doesn't seem to help with mps

**Comment by Vincent-liuwingsang** [comment]
further investigation suggests that poor performance is related to my code.
I'm using watchdog to run `embeddings.upsert` on file creation and that seemed to 10x the  run time for `embeddings.upsert`. I'm not entirely sure why but likely to something to do with threading.

Closing this as a result

**Comment by davidmezzetti** [comment]
Thank you for the discussion. While it might not help in this specific situation, #488 and #489 were added to help improve txtai overall.
