### ISSUE TITLE
Question about BM25 with respect to the scoring parameter and the ScoringFactory class

### ISSUE THREAD

**Issue by doxgazwaz** [neuml/txtai#490]
Hi! Great library. I'm just exploring around informational retrieval libraries. I tried only gensim and sklearn tfidf so I'm pretty new here. Just want to ask the difference between using bm25 as scoring and without because they seem giving the same output and scores. I had an impression they be doing like hybrid search kind of thing like in pinecone.

```python
#without using bm25
embeddings_batch = Embeddings({"path": "sentence-transformers/all-MiniLM-L6-v2", "content": True, "object": True})
start = time.time()
embeddings_batch.index(stream_products_tqdm())
print(f"Indexing took {time.time() - start} seconds")
embeddings_batch.search('hammer',5)
```

```python
# using bm25
embeddings_batch_bm25 = Embeddings({"path": "sentence-transformers/all-MiniLM-L6-v2", "scoring":"bm25", "content": True, "object": True})
start = time.time()
embeddings_batch_bm25.score(stream_products_tqdm())
embeddings_batch_bm25.index(stream_products_tqdm())
print(f"Indexing took {time.time() - start} seconds")
print(embeddings_batch_bm25.info())
embeddings_batch_bm25.search('hammer',5)

## OUTPUT IS THE SAME 
```

also I tried doing bm25 with ScoringFactory,

```python
scoring = ScoringFactory.create({"method": "bm25", "terms": True, "content": True, "normalize": True})
scoring.index(stream_products_tqdm())
```

this two lines gives different results even with the same query

```python
scoring.search("SELECT * FROM txtai WHERE similar('hammer')")
```

```python
scoring.search("hammer")
```

I was interested in doing the sql query approach because I can show the tags for filtering that I used in `stream_products_tqdm()`
which has a function (pseudo-code) of 

```python
for uid, text, metadata in rows:
        if text:
            yield(uid, text, metadata)
```

**Comment by davidmezzetti** [comment]
Thank you for submitting the issue and the nice words on txtai.

BM25 scoring with embeddings is currently designed for Word Vector models at the moment. But in thinking about it, I do think it would be relatively straightforward to incorporate it into a similar clause. I'll take a look and report back.

A scoring instance doesn't have support for SQL, so it runs the literal string in each search call, hence the different results. 

The next major release of txtai will take multi-index embeddings where different columns can have different indexes. So this should be much more streamlined but I do think incorporating BM25 scoring is a task to investigate before that.

**Comment by davidmezzetti** [comment]
Thank you for starting this conversation. BM25 indexes will be an upcoming item in the 6.0 release. Stay tuned!

https://github.com/neuml/txtai/milestone/32
