### ISSUE TITLE
Questions about natural language queries

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [neuml/txtai#491]
1. Whats the best way to retrieve more fields when using natural language queries in one go? (currently it returns only `id`, `text`, `score`)    

2. Currently `Embeddings.save` doesn't save `query` config. if I pass `query` when initialising `Embeddings`, calling `Embeddings.load` would reset the `query` on the instance. I believe [this](https://github.com/neuml/txtai/blob/5ed0a3c52b2c16c963a81d103d3ffd387c2a0123/src/python/txtai/embeddings/base.py#L490) should do a merge instead 🤔

3. It seems like time-based naturual language queries like "XXXX from last 5 hour" will always translate to `date('now', '-5 hours')` when it should be `DateTime('now', '-5 hours')`. I'm assuming to fix this, I will need to train the query model?

4. Is it possible to use natural language to query on multiple fields? for example if I'm indexing data like `{"text": "icecream", "location": "Michigan"}` and wanting to get them with queries like "desert" or "desert in New York" or "Michigan".

5. Similar to 3 and 4, if I want to translate "XXX from last 5 hours" and match on something like `data.cutsom_timestamp` in stead of `entry`, is is best to retrain the model?

**Comment by davidmezzetti** [comment]
The natural language queries are catered towards a couple of common use cases. The code used to build [t5-small-txtsql](https://huggingface.co/NeuML/t5-small-txtsql) can be found [here](https://github.com/neuml/txtinstruct/blob/master/src/python/txtinstruct/models/txtsql.py). I think to get the exact syntax you're looking for in 1, 3, 4 and 5 training your own model is the way to go.

Regarding 2, the embeddings instance is designed to fully clear the object when calling `load`. If you'd like to update the config, the best way to do that is load the embeddings instance first then override values on embeddings.config.

**Comment by Vincent-liuwingsang** [comment]
@davidmezzetti thanks for the reply. Great feedback👍
