### ISSUE TITLE
txtai for .NET

### ISSUE THREAD

**Issue by semack** [neuml/txtai#497]
Just FYI, I've ported Java client to .NET
https://github.com/semack/TxtAI.NET

I'm ready to transfer it to you guys, if you need it.  

The package is already deployed to NUGET
https://www.nuget.org/packages/TxtAI.NET

**Comment by davidmezzetti** [comment]
Thank you for creating and sharing this project!

If you're comfortable continuing to maintain it, that's for the best. There are similar situations out there such as [weaviate-txtai](https://github.com/hsm207/weaviate-txtai), [qdrant-txtai](https://github.com/qdrant/qdrant-txtai) and [txtai for conda](https://anaconda.org/conda-forge/txtai)

**Comment by semack** [comment]
Thanks. Ok, I'll try to keep it on track.
