### ISSUE TITLE
Can we have a CONTRIBUTING.md for a quick guide?

### ISSUE THREAD

**Issue by sohamsshah** [neuml/txtai#50]
It can have sections such as:

- To contribute a feature/fix
- How can you help
- Getting Started
- Formatting and Linting rules
- Connect on Slack etc. to get help or for issues

P.S. I am new to NeuML and found this an interesting initiative. Would love to contribute!

**Comment by davidmezzetti** [comment]
Great idea, will work on this after the next release.

**Comment by sohamsshah** [comment]
Awesome. Is there any issue/feature that I can help with?

**Comment by davidmezzetti** [comment]
CONTRIBUTING guide is now out there, thank you for the idea. There isn't a feature/issue that is a good first issue at this point but I'll keep an eye out for one.
