### ISSUE TITLE
ScoringFactory does not support Chinese

### ISSUE THREAD

**Issue by jqsl2012** [neuml/txtai#506]
I refer to the following document：
https://github.com/neuml/txtai/blob/master/examples/39_Classic_Topic_Modeling_with_BM25.ipynb

Let me replace the data set with Chinese, and I can't find any results。

I tried to read the source code and found that token processing does not support Chinese?

```
Tokenizer.tokenize(data)
return [token for token in tokens if re.match(r"^\d*[a-z][\-.0-9:_a-z]{1,}$", token) and token not in Tokenizer.STOP_WORDS]
```

**Comment by davidmezzetti** [comment]
Thank you for sharing. #507 and #508 will address this in the upcoming 6.0 release.

**Comment by jqsl2012** [comment]
@davidmezzetti  Thank you
