### ISSUE TITLE
Problems on tutorial 3

### ISSUE THREAD

**Issue by gillsgills** [neuml/txtai#528]
I am learning vector database by this amazing toolkit. However, when I met tutorial 3, I found it has an incomplete sentence: 
```
While not quite as powerful as transformer embeddings, they often provide a g
```
I know what transformer embeddings usually can bring so I guess similar content can be fed?

**Comment by davidmezzetti** [comment]
Thanks for both noticing and reporting this issue in the notebook. This was a leftover sentence from a change that happened over 2 years ago!
