### ISSUE TITLE
Is it possible to filter the graph before or when walking the graph?

### ISSUE THREAD

**Issue by dustyatx** [neuml/txtai#534]
First let me say I finally got my first graph built and WOW.. It took me a few attempts to figure out how best to get the data structured to get a high level of accuracy between the nodes.. The results were well worth the effort, I've never seen anything that can do this before. I can walk the graph between a concept like "Consumer demand index" and "Inflation impact to pricing" and get a really good string of inter-related topics that bridge the two concepts. 

Now I'm trying to get the next more complex queries worked out beyond showpath(source, destination). 

I've figured out how to create nodes and then update those nodes with new keys and values. Now I'm wondering if there is a way to use the information in those values to control how I walk the graph?

I'd like to have a graph with different types of data attached to the node and then use them to filter out what I am walking. A basic example would be to only show nodes that have have a date between x & y but I'd also like to use categories, only show nodes about an entity or nodes with a specific category. 

Ideally I can do something like. 
Walk the graph between text that talks about supply chain problems and then only walk nodes that have been categorized as having information about supply chain (which is stored in an array called categories in the node, between July & August of 2023. Is there a way to do this with edges? I can label an edge "does business with" and then use that to filter what I walk? 

If this is possible, I'm would love some other suggestions on what else is possible. The documentation isn't clear what capabilities that I can use to craft graph queries.

**Comment by davidmezzetti** [comment]
First off, glad you're seeing some success with the graph! It sounds like you're applying it in interesting ways. I'll have to think more about this.

Did you have thoughts on #525? Would that be helpful in adding manually defined relationships?

**Comment by dustyatx** [comment]
Sorry for the slow response.. I'm pretty much working two full time jobs right now.. my day job and my project.
