### ISSUE TITLE
Why do memory usages differ by 3Gb in these 2 scenarios?

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [neuml/txtai#537]
scenario 1 where I pull the agnews dataset(60Mb) and save first 10K into an index. It takes about 4.32Gb in memory after completion.

scenario 2 where I load from the same path and only takes about 1.4 Gb.

Why is there a difference here? 

```
scenario 1 - 4.32Gb
# Build hybrid index
embeddings = txtai.Embeddings({
    "method": "sentence-transformers",
    "path": "BAAI/bge-small-en",
    "content": True,
    "hybrid": False,
    "backend": "faiss",
    # "faiss": {
    #   "mmap": True,
    # }
})
embeddings.index(stream(dataset, "text", 10000))
embeddings.save("location")
embeddings.search("Kennedy")

scenario 2 - 1.42Gb
embeddings = Embeddings()
embeddings.load("/Users/wingsangvincentliu/Documents/UnlostApp.nosync/txtai_hybrid_false_mmap_true")
embeddings.search("Kennedy")
```

**Comment by Vincent-liuwingsang** [comment]
The reason I'm asking this as I have an index that gets updated and queries in realtime and noticed it always come down quite a bit when restarting

**Comment by Vincent-liuwingsang** [comment]
I was just checking the activity monitor memory usage which might not actually not be equivalent to [real memory](https://apple.stackexchange.com/questions/362249/what-is-the-difference-between-memory-real-mem-and-compressed-mem)

running `int(psutil.Process().memory_info().rss / (1024 * 1024))` on the scenarios both give
scenario 1 -  4xx
scenario 2 - 8xx that goes back to 4xx after gc it seems

closing as I think I was just mislead by activity monitor on Mac

**Comment by Vincent-liuwingsang** [comment]
could this be [memory fragmentation](https://stackoverflow.com/questions/16616389/python-process-consuming-increasing-amounts-of-system-memory-but-heapy-shows-ro) 🤔

**Comment by davidmezzetti** [comment]
Really can't help on this as I don't develop on a Mac. I know with Linux, releasing memory doesn't necessarily mean it will be returned by the OS right away. OS memory management can get quite complex. Python does have memory profiling tools that you can also use to inspect what's being held on to. 

If this is more an academic curiosity thing, I would try using Hnswlib to see how that behaves vs Faiss. And try keyword only to see how those behave.

**Comment by Vincent-liuwingsang** [comment]
interesting finding. Downgrading to txtai 5.5.1 with the same piece of code doesn't have the memory issue

**Comment by davidmezzetti** [comment]
I don't know on this one. For me when I run that code process 2 temporarily has less memory used but it jumps up to the same value once I run a search.

**Comment by Vincent-liuwingsang** [comment]
just scanned through the commits I can't find anything suspicious 😔

I noticed a significant performance gain on embedding indexing in v6 comparing to v5. (almost twice as fast on v6)
Which commit made the gain happen?

Keen to check that out

**Comment by davidmezzetti** [comment]
The most likely change given you're running on a mac is #489. This added support for MPS devices.

**Comment by Vincent-liuwingsang** [comment]
ok yeah that makes sense didn't realise gpu defaults to true🤦🏻

Another interesting finding pertinent to MacOS, disabling gpu doesn't have the memory issue above

**Comment by davidmezzetti** [comment]
Perhaps the puzzle is now coming together.

I don't know a ton about MPS devices but from what I've read, I believe it adopts a unified memory architecture. So shared memory between CPU/GPU. Wonder if that incurs a cost. 

Here is an article I quickly found. 

https://www.mbsdirect.com/mbs-blog/article-how-much-memory-do-you-need-in-an-m1-based-mac

**Comment by Vincent-liuwingsang** [comment]
experimented with scenario 1 above and immediately execute the following code. 2.3Gb of memory for basically nothing is strange. This might take a while to figure out as I don't really understand how gc'ing all the objects and emptying gpu cache would still occupy 2Gb of memory
```
# 4.3 Gb
import gc

del embeddings
gc.collect()
# 3.3 Gb

from torch import mps
mps.empty_cache()
# 2.3 Gb
```

**Comment by davidmezzetti** [comment]
Closing as there doesn't appear to be any further action on this, at least related to txtai.
