### ISSUE TITLE
I am trying to get run embeddings.explain method but it gives an empty output. 

### ISSUE THREAD

**Issue by DenuwanClouda** [neuml/txtai#538]
Thank you for an amazing library. Please help me with the following issue

I am trying to do semantic search. I created an index using product IDs as the index ids and encoded reviewText as values in the index. After doing the search, I accurately get the search results. But when I run the query with embeddings.explain method, it returns an empty list.

Following is the code

#### import the packages
from txtai.embeddings import Embeddings

#### Create embeddings model, backed by sentence-transformers & transformers
embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2"})

#### extract first element
first_element = df_dict[:1]
df_dict = df_dict[1:]

#### index the data
embeddings.index([(first_element[0]['asin'], first_element[0]['reviewText'], None)])

for item in tqdm(df_dict, desc="Indexing"):
  embeddings.upsert([(item['asin'], item['reviewText'], None)])

#### now instead of similarity, use search function
embeddings.search("Movie which has great music", limit=2)

#### explanation
embeddings.explain("Movie which has great music", limit=2)

##### output to last cell above -> [ ]

**Comment by davidmezzetti** [comment]
Thank you for taking the time to submit an issue.

The `explain` method requires either `content` to be set to `True` or the list of texts to be provided. I just updated the documentation to note this.

So either:

```python
embeddings = Embeddings({"path": "sentence-transformers/nli-mpnet-base-v2", "content": True})
```

or

```python
embeddings.explain("query", [externally resolved list of text results])
```
