### ISSUE TITLE
Storing several Embeddings under a single index

### ISSUE THREAD

**Issue by DenuwanClouda** [neuml/txtai#539]
Thank you for this amazing work you have done for the semantic search NLP task by introducing such an amazing tool.

I would like to know is there a way I can store several embeddings under a single index? 

Example:
I have a review dataset that has reviews on products. Each row corresponds to a certain review for a product. Single product can have multiple reviews (several rows). So I am trying to embed these results using a transformer and store them in a vector index. When I search for a product using a search query, I want to consider(using cosine similarity) every review for a particular product before recommending it. 

Is this possible? in your tool. If my approach is not possible (storing several embeddings/reviews under single index/product) can you suggest an implementation I can use using txtai tools?

**Comment by davidmezzetti** [comment]
A txtai index supports an id having multiple entries as shown below.

```python
embeddings.index([(product id 1, "review 1", None), (product id 1, "review 2", None)])
```

There is also the subindexes feature:

https://neuml.github.io/txtai/embeddings/configuration/general/#indexes
https://medium.com/neuml/whats-new-in-txtai-6-0-7d93eeedf804

#524 had a discussion on subindexes.

Hopefully, one of these options could accomplish what you're looking to do.

**Comment by DenuwanClouda** [comment]
Thank you for the reply. This could work in my case.
