### ISSUE TITLE
Encoding of data as dictionary

### ISSUE THREAD

**Issue by DenuwanClouda** [neuml/txtai#545]
<img width="909" alt="image" src="https://github.com/neuml/txtai/assets/141103329/cf62b6e7-8131-401d-aa94-1d1da79e9a19">

<img width="1412" alt="image" src="https://github.com/neuml/txtai/assets/141103329/da9ff612-070a-4236-9391-28de6f935766">

1. If I create the index like above, when the encoding happens, which fields get encoded into vectors? All the fields or only the "text "field?
2. When I give field names in the dictionary item passed when creating index, if I omit the field "text", indexing will not happen, why?

**Comment by davidmezzetti** [comment]
The default behavior encodes the `text` field. This field is configurable as discussed in #524 and #539.

Each embeddings index can only index a single field. You can either create a concatenated field or create separate subindexes for each field.

**Comment by DenuwanClouda** [comment]
Thank you for the reply. I have another question. Is it possible to work with more than two indexes? With weights?

**Comment by davidmezzetti** [comment]
Subindexes are currently equally weighted at query time. Hybrid indexes have an option to control the weights between sparse and dense indexes. 

Did you need to weight indexes differently than those options above?

**Comment by DenuwanClouda** [comment]
@davidmezzetti  What I mean is, if I initiate something as below
<img width="523" alt="image" src="https://github.com/neuml/txtai/assets/141103329/77248366-a77f-488b-a3ec-e73138b38eb2">
Will I be able to search as below
<img width="568" alt="image" src="https://github.com/neuml/txtai/assets/141103329/22b28f98-2e5b-4d6f-9112-ce8b381a6ae2">
What I want is to apply weight to the selected hybrid indexes.

Also let's say there are several hybrid indexes I initiated in the Embeddings object, will I be able to pass weights to them in a list, when I search?

Is such a thing possible ?

**Comment by davidmezzetti** [comment]
First off, I'm glad to see how you're using subindexes. This is exactly as I intended when it was developed, so it's great to see it in practice.

If I understand you correctly, you want to set the weights on each similar call. You can pass an additional argument to each one to set the weights for that call. For example: `similar({query}, 'title', 0.25)`  would set the weights as `0.25` for the `dense` index and `0.75` for the `sparse` index.

If you're looking to set the weights between each of the similar clauses, that is not currently supported. Each similar clause is equally weighted in the final score.

**Comment by DenuwanClouda** [comment]
Thank you for the response and for the implementation of this feature. The suggested method could work in my case.

**Comment by davidmezzetti** [comment]
Closing as there doesn't appear to be any further action on this.
