### ISSUE TITLE
Integrate with Litellm

### ISSUE THREAD

**Issue by ranjancse26** [neuml/txtai#554]
I believe, it's a great idea to incorporate the txtai with the Litellm as it already supports Intergrations with 100+ LLMs.

https://github.com/BerriAI/litellm

LLM as drop-in replacement for gpt-3.5-turbo. Use Azure, OpenAI, Cohere, Anthropic, Ollama, VLLM, Sagemaker, HuggingFace, Replicate (100+ LLMs)

cc @ishaan-jaff

**Comment by davidmezzetti** [comment]
Thank you for the suggestion, I think it's a good idea. I'll try to work this in the next release or two. 

I could see this integrating with this class: https://github.com/neuml/txtai/blob/master/src/python/txtai/pipeline/text/llm.py
