### ISSUE TITLE
url parsing for connection string is not working

### ISSUE THREAD

**Issue by DenuwanClouda** [neuml/txtai#556]
I tried to connect a mysql database through a connection string. I installed txtai[database] through pip. But the loaded txtai version is not updated unlike in the github repository. 
loaded throgh pip:
<img width="1106" alt="image" src="https://github.com/neuml/txtai/assets/141103329/2b237a7a-98bd-4983-a346-e7276a89c144">
in above picture as seen, the url is not being parsed. But as seen in below, code in the git repo seems to be properly doing that.
<img width="614" alt="image" src="https://github.com/neuml/txtai/assets/141103329/84ee1449-ed8b-403f-ba7b-3a05731c6305">

**Comment by davidmezzetti** [comment]
This feature is only available in the main branch as it's due to be released with txtai 6.1

If you want to try it out, you can [install txtai as shown in this link](https://neuml.github.io/txtai/install/#install-from-source).

**Comment by DenuwanClouda** [comment]
@davidmezzetti I see. I tried what you mentioned also. It didn't work somehow. But eventually it worked for the following:
- ` pip install git+https://github.com/neuml/txtai#egg=txtai[database] `
- This was found when I was trying out [one of the examples](https://github.com/neuml/txtai/blob/master/examples/49_External_database_integration.ipynb) in txtai repository. 
</br>

This was needed while I was trying to connect an mysql external server to this. Regarding that, is it possible to connect MongoDB? In the example I linked above, says that only SQL databases are allowed. But is there any feature or at least a work around for that?

**Comment by davidmezzetti** [comment]
Closing as there doesn't appear to be any further action on this.

MongoDB is not supported by SQLAlchemy. It's possible that MongoDB could be added but that would be a separate initiative.
