### ISSUE TITLE
how to extract embedding vectors from a loaded index

### ISSUE THREAD

**Issue by EnricoScquiz** [neuml/txtai#560]
Hi, i'm following te initial tutorial to create an index for my embeddings, save it in a local folder and then load it whenever i want.

I use these lines of code to create index and save it:

embeddings = Embeddings(path="sentence-transformers/multi-qa-MiniLM-L6-cos-v1")
embeddings.index(documents=df.X)
embeddings.save(path="embeddings_saved")

then to load it:
embeddings = Embeddings(path="sentence-transformers/multi-qa-MiniLM-L6-cos-v1")
Embeddings.load(embeddings, path="embeddings_saved")

How can i get the vectors for each document?
I need them for a classification task

**Comment by davidmezzetti** [comment]
The default ANN store Faiss doesn't store the raw vectors. If you want the vectors, you can try a different ANN. For example:

```python
embeddings = Embeddings(path="sentence-transformers/multi-qa-MiniLM-L6-cos-v1", "backend"="numpy")
embeddings.index(documents=df.X)

# This is a NumPy array with all the vectors
embeddings.ann.backend
```

**Comment by EnricoScquiz** [comment]
Thanks a lot

**Comment by EnricoScquiz** [comment]
> Hi, i'm following te initial tutorial to create an index for my embeddings, save it in a local folder and then load it whenever i want.
> 
> I use these lines of code to create index and save it:
> 
> embeddings = Embeddings(path="sentence-transformers/multi-qa-MiniLM-L6-cos-v1") embeddings.index(documents=df.X) embeddings.save(path="embeddings_saved")
> 
> then to load it: embeddings = Embeddings(path="sentence-transformers/multi-qa-MiniLM-L6-cos-v1") Embeddings.load(embeddings, path="embeddings_saved")
> 
> How can i get the vectors for each document? I need them for a classification task
