### ISSUE TITLE
Dates fail in example 

### ISSUE THREAD

**Issue by rickknowles-cognitant** [neuml/txtai#563]
Hi,

I just tried the examples in the following page: https://neuml.github.io/txtai/embeddings/query/ and found it did something wrong with dates:

```
desktop:~/txtai$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from txtai.embeddings import Embeddings
>>> embeddings = Embeddings(path="sentence-transformers/nli-mpnet-base-v2", content=True)
>>> embeddings.index([{"text": "text to index", "flag": True, "entry": "2022-01-01"}])
>>> embeddings.search("SELECT text, flag, entry FROM txtai WHERE similar('query') AND flag = 1 AND entry >= '2022-01-01'")
[{'text': 'text to index', 'flag': 1, 'entry': '2023-09-23 15:21:29.714090'}]
```

As you can see the act of inserting a date inserts the current date regardless of what's supplied (check the date of "entry" during insert and then on return from querying).

The expected result for the last "search" command should be 
```
[{'text': 'text to index', 'flag': 1, 'entry': '2022-01-01 00:00:00.000000'}]
```
shouldn't it ?

**Comment by davidmezzetti** [comment]
Hello,

Thanks for this catch. `entry` is a standard field and will be preferred over any custom field. If you give it a different name it will work as expected.

I'll update the documentation to fix this.

**Comment by rickknowles-cognitant** [comment]
ah ok thanks - it might be worth updating the text in the example page listed not to use this name then (if you haven't already)
