### ISSUE TITLE
Stuck in loop with installing txtai[pipeline]

### ISSUE THREAD

**Issue by noiraku** [neuml/txtai#572]
It fails installing the fasttext, i tried every way to make it pass but no, install pyproject.toml doesnt work, fasttext-wheel doesnt work either, tried older versions but im literally new on this debugging installation i have no idea and im lost.
Anyway to install this? :(
Im using venv

> pip install txtai[pipeline]
> Requirement already satisfied: txtai[pipeline] in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (6.1.0)
> Requirement already satisfied: faiss-cpu>=1.7.1.post2 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (1.7.4)
> Requirement already satisfied: torch>=1.12.1 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (2.1.0)
> Requirement already satisfied: transformers>=4.22.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (4.34.0)
> Requirement already satisfied: huggingface-hub>=0.9.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (0.17.3)
> Requirement already satisfied: numpy>=1.18.4 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (1.26.0)
> Requirement already satisfied: pyyaml>=5.3 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (6.0.1)
> Requirement already satisfied: regex>=2022.8.17 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (2023.10.3)
> Collecting onnx>=1.11.0 (from txtai[pipeline])
>   Obtaining dependency information for onnx>=1.11.0 from https://files.pythonhosted.org/packages/00/36/e7a7e7a85564e7d409e4e8addfa11d41015d2190bfff30064771e7c21ca0/onnx-1.14.1-cp310-cp310-win_amd64.whl.metadata
>   Using cached onnx-1.14.1-cp310-cp310-win_amd64.whl.metadata (15 kB)
> Collecting onnxruntime>=1.11.0 (from txtai[pipeline])
>   Obtaining dependency information for onnxruntime>=1.11.0 from https://files.pythonhosted.org/packages/e6/b5/34dee2624c30325377271d0f3d18dbb54f1d413f7af1d505a5b5ddb4ae5e/onnxruntime-1.16.0-cp310-cp310-win_amd64.whl.metadata
>   Using cached onnxruntime-1.16.0-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
> Collecting soundfile>=0.10.3.post1 (from txtai[pipeline])
>   Using cached soundfile-0.12.1-py2.py3-none-win_amd64.whl (1.0 MB)
> Collecting scipy>=1.4.1 (from txtai[pipeline])
>   Obtaining dependency information for scipy>=1.4.1 from https://files.pythonhosted.org/packages/3a/98/3041681b3a0fef0f59033861a05d846aa1d284b07b531ce35b1b97cc2e93/scipy-1.11.3-cp310-cp310-win_amd64.whl.metadata
>   Using cached scipy-1.11.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
> Collecting ttstokenizer>=1.0.0 (from txtai[pipeline])
>   Using cached ttstokenizer-1.0.0-py3-none-any.whl (3.1 MB)
> Requirement already satisfied: beautifulsoup4>=4.9.3 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (4.12.2)
> Requirement already satisfied: nltk>=3.5 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from txtai[pipeline]) (3.8.1)
> Collecting pandas>=1.1.0 (from txtai[pipeline])
>   Obtaining dependency information for pandas>=1.1.0 from https://files.pythonhosted.org/packages/ce/cd/a7c2cbffe2afff975349e60b14b63a448162145a7acac8ba12ddc2ed78a8/pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata
>   Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata (18 kB)
> Collecting tika>=1.24 (from txtai[pipeline])
>   Using cached tika-2.6.0-py3-none-any.whl
> Collecting imagehash>=4.2.1 (from txtai[pipeline])
>   Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
> Collecting pillow>=7.1.2 (from txtai[pipeline])
>   Obtaining dependency information for pillow>=7.1.2 from https://files.pythonhosted.org/packages/23/ca/7296d769f62266c0f94bf76496bc77114e7a96d2de3d7bcba91d0ba2856f/Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata
>   Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl.metadata (9.6 kB)
> Collecting timm>=0.4.12 (from txtai[pipeline])
>   Obtaining dependency information for timm>=0.4.12 from https://files.pythonhosted.org/packages/7a/bd/2c56be7a3b5bc71cf85a405246b89d5359f942c9f7fb6db6306d9d056092/timm-0.9.7-py3-none-any.whl.metadata
>   Using cached timm-0.9.7-py3-none-any.whl.metadata (58 kB)
> Collecting fasttext>=0.9.2 (from txtai[pipeline])
>   Using cached fasttext-0.9.2.tar.gz (68 kB)
>   Preparing metadata (setup.py) ... done
> Collecting sentencepiece>=0.1.91 (from txtai[pipeline])
>   Using cached sentencepiece-0.1.99-cp310-cp310-win_amd64.whl (977 kB)
> Collecting accelerate>=0.19.0 (from txtai[pipeline])
>   Obtaining dependency information for accelerate>=0.19.0 from https://files.pythonhosted.org/packages/d9/92/2d3aecf9f4a192968035880be3e2fc8b48d541c7128f7c936f430d6f96da/accelerate-0.23.0-py3-none-any.whl.metadata
>   Using cached accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
> Collecting onnxmltools>=1.9.1 (from txtai[pipeline])
>   Using cached onnxmltools-1.11.2-py2.py3-none-any.whl (322 kB)
> Requirement already satisfied: packaging>=20.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from accelerate>=0.19.0->txtai[pipeline]) (23.2)
> Collecting psutil (from accelerate>=0.19.0->txtai[pipeline])
>   Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
> Requirement already satisfied: soupsieve>1.2 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from beautifulsoup4>=4.9.3->txtai[pipeline]) (2.5)
> Requirement already satisfied: pybind11>=2.2 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from fasttext>=0.9.2->txtai[pipeline]) (2.11.1)
> Requirement already satisfied: setuptools>=0.7.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from fasttext>=0.9.2->txtai[pipeline]) (65.5.0)
> Requirement already satisfied: filelock in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from huggingface-hub>=0.9.0->txtai[pipeline]) (3.12.4)
> Requirement already satisfied: fsspec in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from huggingface-hub>=0.9.0->txtai[pipeline]) (2023.9.2)
> Requirement already satisfied: requests in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from huggingface-hub>=0.9.0->txtai[pipeline]) (2.31.0)
> Requirement already satisfied: tqdm>=4.42.1 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from huggingface-hub>=0.9.0->txtai[pipeline]) (4.66.1)
> Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from huggingface-hub>=0.9.0->txtai[pipeline]) (4.8.0)
> Collecting PyWavelets (from imagehash>=4.2.1->txtai[pipeline])
>   Using cached PyWavelets-1.4.1-cp310-cp310-win_amd64.whl (4.2 MB)
> Requirement already satisfied: click in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from nltk>=3.5->txtai[pipeline]) (8.1.7)
> Requirement already satisfied: joblib in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from nltk>=3.5->txtai[pipeline]) (1.3.2)
> Collecting protobuf>=3.20.2 (from onnx>=1.11.0->txtai[pipeline])
>   Obtaining dependency information for protobuf>=3.20.2 from https://files.pythonhosted.org/packages/c2/59/f89c04923d68595d359f4cd7adbbdf5e5d791257945f8873d88b2fd1f979/protobuf-4.24.4-cp310-abi3-win_amd64.whl.metadata
>   Using cached protobuf-4.24.4-cp310-abi3-win_amd64.whl.metadata (540 bytes)
> Collecting skl2onnx (from onnxmltools>=1.9.1->txtai[pipeline])
>   Obtaining dependency information for skl2onnx from https://files.pythonhosted.org/packages/c0/d1/ef96f715f14ab4a11a4382e3eb9fc7a57ee59e3527253a7b21d62ca20402/skl2onnx-1.15.0-py2.py3-none-any.whl.metadata
>   Using cached skl2onnx-1.15.0-py2.py3-none-any.whl.metadata (2.3 kB)
> Collecting coloredlogs (from onnxruntime>=1.11.0->txtai[pipeline])
>   Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
> Collecting flatbuffers (from onnxruntime>=1.11.0->txtai[pipeline])
>   Obtaining dependency information for flatbuffers from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
>   Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
> Requirement already satisfied: sympy in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from onnxruntime>=1.11.0->txtai[pipeline]) (1.12)
> Collecting python-dateutil>=2.8.2 (from pandas>=1.1.0->txtai[pipeline])
>   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)     
> Collecting pytz>=2020.1 (from pandas>=1.1.0->txtai[pipeline])
>   Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
>   Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
> Collecting tzdata>=2022.1 (from pandas>=1.1.0->txtai[pipeline])
>   Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
> Collecting cffi>=1.0 (from soundfile>=0.10.3.post1->txtai[pipeline])
>   Obtaining dependency information for cffi>=1.0 from https://files.pythonhosted.org/packages/be/3e/0b197d1bfbf386a90786b251dbf2634a15f2ea3d4e4070e99c7d1c7689cf/cffi-1.16.0-cp310-cp310-win_amd64.whl.metadata
>   Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl.metadata (1.5 kB)
> Collecting torchvision (from timm>=0.4.12->txtai[pipeline])
>   Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/59/af/426c2b90f5c4f8aba778746465af9e662680570e950e02379e91c6138285/torchvision-0.16.0-cp310-cp310-win_amd64.whl.metadata
>   Using cached torchvision-0.16.0-cp310-cp310-win_amd64.whl.metadata (6.6 kB)
> Requirement already satisfied: safetensors in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from timm>=0.4.12->txtai[pipeline]) (0.4.0)
> Requirement already satisfied: networkx in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from torch>=1.12.1->txtai[pipeline]) (3.1)
> Requirement already satisfied: jinja2 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from torch>=1.12.1->txtai[pipeline]) (3.1.2)
> Requirement already satisfied: tokenizers<0.15,>=0.14 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from transformers>=4.22.0->txtai[pipeline]) (0.14.1)
> Collecting anyascii>=0.3.1 (from ttstokenizer>=1.0.0->txtai[pipeline])
>   Using cached anyascii-0.3.2-py3-none-any.whl (289 kB)
> Collecting inflect>=0.3.1 (from ttstokenizer>=1.0.0->txtai[pipeline])
>   Obtaining dependency information for inflect>=0.3.1 from https://files.pythonhosted.org/packages/fb/c6/d9feb758be584f729424390af24687d3a4363d968164f94079f83cd536b4/inflect-7.0.0-py3-none-any.whl.metadata
>   Using cached inflect-7.0.0-py3-none-any.whl.metadata (21 kB)
> Collecting pycparser (from cffi>=1.0->soundfile>=0.10.3.post1->txtai[pipeline])
>   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
> Requirement already satisfied: pydantic>=1.9.1 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from inflect>=0.3.1->ttstokenizer>=1.0.0->txtai[pipeline]) (2.4.2)
> Requirement already satisfied: six>=1.5 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.0->txtai[pipeline]) (1.16.0)
> Requirement already satisfied: colorama in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.9.0->txtai[pipeline]) (0.4.6)
> Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.11.0->txtai[pipeline])
>   Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
> Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from jinja2->torch>=1.12.1->txtai[pipeline]) (2.1.3)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from requests->huggingface-hub>=0.9.0->txtai[pipeline]) (3.3.0)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from requests->huggingface-hub>=0.9.0->txtai[pipeline]) (3.4)
> Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from requests->huggingface-hub>=0.9.0->txtai[pipeline]) (2.0.6)    
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from requests->huggingface-hub>=0.9.0->txtai[pipeline]) (2023.7.22)
> Collecting scikit-learn>=0.19 (from skl2onnx->onnxmltools>=1.9.1->txtai[pipeline])
>   Obtaining dependency information for scikit-learn>=0.19 from https://files.pythonhosted.org/packages/59/ed/548f6f686845d386a727a51a3daa411d95fc599649a2d54705f6773ac259/scikit_learn-1.3.1-cp310-cp310-win_amd64.whl.metadata
>   Using cached scikit_learn-1.3.1-cp310-cp310-win_amd64.whl.metadata (11 kB)
> Collecting onnxconverter-common>=1.7.0 (from skl2onnx->onnxmltools>=1.9.1->txtai[pipeline])
>   Obtaining dependency information for onnxconverter-common>=1.7.0 from https://files.pythonhosted.org/packages/6d/6a/9ed9fd4da34cb41fda35bc5cc9e990c605689db7de63ed84fedbca5a77f6/onnxconverter_common-1.14.0-py2.py3-none-any.whl.metadata
>   Using cached onnxconverter_common-1.14.0-py2.py3-none-any.whl.metadata (4.2 kB)
> Requirement already satisfied: mpmath>=0.19 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from sympy->onnxruntime>=1.11.0->txtai[pipeline]) (1.3.0)
> Collecting pyreadline3 (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.11.0->txtai[pipeline])
>   Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
> Collecting protobuf>=3.20.2 (from onnx>=1.11.0->txtai[pipeline])
>   Using cached protobuf-3.20.2-cp310-cp310-win_amd64.whl (904 kB)
> Requirement already satisfied: annotated-types>=0.4.0 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from pydantic>=1.9.1->inflect>=0.3.1->ttstokenizer>=1.0.0->txtai[pipeline]) (0.5.0)
> Requirement already satisfied: pydantic-core==2.10.1 in c:\users\administrator\desktop\noiraaidcbot\.venv\lib\site-packages (from pydantic>=1.9.1->inflect>=0.3.1->ttstokenizer>=1.0.0->txtai[pipeline]) (2.10.1)
> Collecting threadpoolctl>=2.0.0 (from scikit-learn>=0.19->skl2onnx->onnxmltools>=1.9.1->txtai[pipeline])
>   Obtaining dependency information for threadpoolctl>=2.0.0 from https://files.pythonhosted.org/packages/81/12/fd4dea011af9d69e1cad05c75f3f7202cdcbeac9b712eea58ca779a72865/threadpoolctl-3.2.0-py3-none-any.whl.metadata
>   Using cached threadpoolctl-3.2.0-py3-none-any.whl.metadata (10.0 kB)
> Using cached accelerate-0.23.0-py3-none-any.whl (258 kB)
> Using cached onnx-1.14.1-cp310-cp310-win_amd64.whl (13.3 MB)
> Using cached onnxruntime-1.16.0-cp310-cp310-win_amd64.whl (7.2 MB)
> Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)
> Using cached Pillow-10.0.1-cp310-cp310-win_amd64.whl (2.5 MB)
> Using cached scipy-1.11.3-cp310-cp310-win_amd64.whl (44.1 MB)
> Using cached timm-0.9.7-py3-none-any.whl (2.2 MB)
> Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
> Using cached inflect-7.0.0-py3-none-any.whl (34 kB)
> Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
> Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
> Using cached skl2onnx-1.15.0-py2.py3-none-any.whl (294 kB)
> Using cached torchvision-0.16.0-cp310-cp310-win_amd64.whl (1.3 MB)
> Using cached onnxconverter_common-1.14.0-py2.py3-none-any.whl (84 kB)
> Using cached scikit_learn-1.3.1-cp310-cp310-win_amd64.whl (9.3 MB)
> Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
> Building wheels for collected packages: fasttext
>   Building wheel for fasttext (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [52 lines of output]
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
>         warnings.warn(
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-310
>       creating build\lib.win-amd64-cpython-310\fasttext
>       copying python\fasttext_module\fasttext\FastText.py -> build\lib.win-amd64-cpython-310\fasttext
>       copying python\fasttext_module\fasttext\__init__.py -> build\lib.win-amd64-cpython-310\fasttext
>       creating build\lib.win-amd64-cpython-310\fasttext\util
>       copying python\fasttext_module\fasttext\util\util.py -> build\lib.win-amd64-cpython-310\fasttext\util
>       copying python\fasttext_module\fasttext\util\__init__.py -> build\lib.win-amd64-cpython-310\fasttext\util
>       creating build\lib.win-amd64-cpython-310\fasttext\tests
>       copying python\fasttext_module\fasttext\tests\test_configurations.py -> build\lib.win-amd64-cpython-310\fasttext\tests
>       copying python\fasttext_module\fasttext\tests\test_script.py -> build\lib.win-amd64-cpython-310\fasttext\tests
>       copying python\fasttext_module\fasttext\tests\__init__.py -> build\lib.win-amd64-cpython-310\fasttext\tests
>       running build_ext
>       building 'fasttext_pybind' extension
>       creating build\temp.win-amd64-cpython-310
>       creating build\temp.win-amd64-cpython-310\Release
>       creating build\temp.win-amd64-cpython-310\Release\python
>       creating build\temp.win-amd64-cpython-310\Release\python\fasttext_module
>       creating build\temp.win-amd64-cpython-310\Release\python\fasttext_module\fasttext
>       creating build\temp.win-amd64-cpython-310\Release\python\fasttext_module\fasttext\pybind
>       creating build\temp.win-amd64-cpython-310\Release\src
>       "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include -Ic:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include -Isrc -Ic:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tppython/fasttext_module/fasttext/pybind/fasttext_pybind.cc /Fobuild\temp.win-amd64-cpython-310\Release\python/fasttext_module/fasttext/pybind/fasttext_pybind.obj /EHsc /DVERSION_INFO=\\\"0.9.2\\\"
>       fasttext_pybind.cc
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(171): error C2065: 'ssize_t': undeclared identifier
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(171): error C2672: 'pybind11::init': no matching overloaded function found
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(170): error C2974: 'pybind11::init': invalid template argument for 'CFunc', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1932): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(170): error C2974: 'pybind11::init': invalid template argument for 'Func', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1924): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(170): error C2974: 'pybind11::init': invalid template argument for 'Args', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1912): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(171): error C2672: 'pybind11::class_<fasttext::Vector>::def': no matching overloaded function found
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(170): error C2780: 'pybind11::class_<fasttext::Vector> &pybind11::class_<fasttext::Vector>::def(const char *,Func &&,const Extra &...)': expects 3 arguments - 1 provided
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1574): note: see declaration of 'pybind11::class_<fasttext::Vector>::def'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(185): error C2065: 'ssize_t': undeclared identifier
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(185): error C2065: 'ssize_t': undeclared identifier
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(185): error C2672: 'pybind11::init': no matching overloaded function found
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(182): error C2974: 'pybind11::init': invalid template argument for 'CFunc', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1932): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(182): error C2974: 'pybind11::init': invalid template argument for 'Func', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1924): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(182): error C2974: 'pybind11::init': invalid template argument for 'Args', type expected
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1912): note: see declaration of 'pybind11::init'
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(185): error C2672: 'pybind11::class_<fasttext::DenseMatrix>::def': no matching overloaded function found
>       python/fasttext_module/fasttext/pybind/fasttext_pybind.cc(182): error C2780: 'pybind11::class_<fasttext::DenseMatrix> &pybind11::class_<fasttext::DenseMatrix>::def(const char *,Func &&,const Extra &...)': expects 3 arguments - 1 provided
>       c:\Users\Administrator\Desktop\NoiraAIDCbot\.venv\lib\site-packages\pybind11\include\pybind11\pybind11.h(1574): note: see declaration of 'pybind11::class_<fasttext::DenseMatrix>::def'
>       error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for fasttext
>   Running setup.py clean for fasttext
> Failed to build fasttext
> ERROR: Could not build wheels for fasttext, which is required to install pyproject.toml-based projects

**Comment by davidmezzetti** [comment]
This issue https://github.com/facebookresearch/fastText/issues/1343 seems to confirm what you've done on Windows & Python 3.10+

You can try to install with Python 3.8/3.9 which doesn't appear to have this issue. I'd recommend commenting on the fastText project to see if they can push a fix to PyPI.

What is the reason you're installing the pipelines extra? What pipeline do you want to use?

**Comment by davidmezzetti** [comment]
Only reason I ask is that you don't need fasttext unless you plan to use the translation pipeline. So you might be OK with just a standard txtai install.
