### ISSUE TITLE
Need urgent help 

### ISSUE THREAD

**Issue by raaj1v** [neuml/txtai#574]
I'm facing issues while creating semantic search for tabular data, Please help me , i tried several changes but not getting luck

```
# Build index with graph subindex
embeddings = txtai.Embeddings(
    content=True,
    defaults=False,
    functions=[
        {"name": "graph", "function": "indexes.act.graph.attribute"}
    ],
    expressions=[
        {"name": "topic", "expression": "graph(indexid, 'topic')"},
    ],
    indexes={
        "keywordProductTenderBrief": {
            "path": "sentence-transformers/quora-distilbert-multilingual",
            "columns": {
                "text": "Keyword",
                "text": "productname",
                "text": "TenderBrief"
            },
            "graph": {
                "topics": {}
            }
        },
        "LocationIndex":{
            "path": "sentence-transformers/quora-distilbert-multilingual",
            "columns": {
                "text": "City",
                "text": "State"
            }
        }
    }
)
```

this is my current embedding generation process as demonstrated in an example. I want to create hybrid semantic search for my tender dataset but the results are not that great, I'm not getting how to create multiple indexes properly or what are their applications. please help

**Comment by raaj1v** [comment]
@davidmezzetti Please have a look sir

**Comment by davidmezzetti** [comment]
I asked a question over on the other issue that may be relevant: https://github.com/neuml/txtai/issues/567#issuecomment-1753804908

Looking at the config, Python doesn't support the format you're entering for the columns fields. The resulting dict will only have a single `text` key with the last value. If you want a compound `text` column, you'll need to create the field yourself in the input data and specify that field.

**Comment by raaj1v** [comment]
I didn't get you, can you please illustrate with an example or demo notebook. that would be great.

**Comment by davidmezzetti** [comment]
I'm closing this issue. I commented over on #567, let's continue the conversation over there.
