### ISSUE TITLE
Is it possible to have 2 embedding models in txtai.embeddings.Embeddings? 

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#578]
Currently, the Embedding method only supports one embedding model 
```
embeddings = Embeddings(path="sentence-transformers/nli-mpnet-base-v2")
```
Is it possible to have 2 embedding models, eg. one to embed images and the other to embed texts in the vector database, so we can search for both images and texts in the same query?

**Comment by davidmezzetti** [comment]
Yes that is possible with subindexes, see the link below. 

- https://medium.com/neuml/whats-new-in-txtai-6-0-7d93eeedf804

**Comment by vnguye65** [comment]
Thank you
