### ISSUE TITLE
Add reranker module such as cross_encoder in sbert to this framework

### ISSUE THREAD

**Issue by svjack** [neuml/txtai#58]
I have review the source code. 
Is it necessary to add a interface about reranker to improve the precision ?

**Comment by svjack** [comment]
> Just released a new version of txtai with a similarity module that is intended for this.
> 
> 
> 
> [Example notebook](https://colab.research.google.com/github/neuml/txtai/blob/master/examples/04_Add_semantic_search_to_Elasticsearch.ipynb)
> 
> 
> 
> I did look at cross encoders but found the bart mnli models gave the best accuracy for the tasks I had. 

i also find sometimes only use bi_encoder without reranker have more accurate conclusion, do you mean this ?

**Comment by davidmezzetti** [comment]
The similarity module is like a cross encoder. It's using a MNLI model to compare the query to each result and finding the best matches.

**Comment by svjack** [comment]
> The similarity module is like a cross encoder. It's using a MNLI model to compare the query to each result and finding the best matches.

you use cos as similarities in batchsearch, i think your model is a bi_encoder model.
when it comes to cross_encoder, you must concat the query with documentation before scoring.

**Comment by davidmezzetti** [comment]
The similarity module is this: https://github.com/neuml/txtai/blob/master/src/python/txtai/pipeline.py#L124

**Comment by davidmezzetti** [comment]
Going to go ahead and close this, thank you for reaching out, feel free to ask more questions as they arise.
