### ISSUE TITLE
Issue with Language Specific Transcription Using txtai and Whisper

### ISSUE THREAD

**Issue by Nondzu** [neuml/txtai#593]
## Environment

- txtai version: 6.2.0
- whisper version: 
- Python version: 3.11.5
- Operating System:
Description:    Linux Mint 21.2
Release:        21.2
Codename:       victoria

## Description

I'm attempting to transcribe Polish audio using the Whisper model within txtai, and while I am able to get transcriptions, they appear to be in English rather than the native language of the audio.

Here's a snippet of the code I'm using:

```python
from txtai.transcription import Transcription

transcribe = Transcription("openai/whisper-large-v2")
for text in transcribe(files):
    print(text)
```

## Questions

1. Does txtai's transcription feature automatically translate the text to English, or is it supposed to return text in the language of the audio?
2. How can I disable any automatic translation feature or specify the language of the audio to ensure that the transcription is in Polish?

Any guidance or suggestions on this matter would be greatly appreciated.

Thank you!

**Comment by Nondzu** [comment]
<img width="724" alt="image" src="https://github.com/neuml/txtai/assets/20000097/f82bed3e-5abb-4440-8ac4-93ed90c937cc">

**Comment by davidmezzetti** [comment]
It's possible Whisper runs the translation task by default. Here's an idea to test out using code from the [model page](https://huggingface.co/openai/whisper-large-v2).

```python
from transformers import WhisperProcessor
from txtai.transcription import Transcription

transcribe = Transcription("openai/whisper-large-v2")

# Test transcribe only
transcribe.pipeline.model.config.forced_decoder_ids = WhisperProcessor.get_decoder_prompt_ids(language="polish", task="transcribe")

for text in transcribe(files):
    print(text)
```

If that works, I can add in a change that makes this more streamlined.

**Comment by Nondzu** [comment]
@davidmezzetti thank you for help, after small mod this code works fine

```
from transformers import WhisperProcessor
from txtai.pipeline import Transcription

# from txtai.transcription import Transcription
# model = "openai/whisper-large-v2"
model = "bardsai/whisper-large-v2-pl-v2"
transcribe = Transcription(model)
processor = WhisperProcessor.from_pretrained(model)
# Test transcribe only
transcribe.pipeline.model.config.forced_decoder_ids = processor.get_decoder_prompt_ids(language="polish", task="transcribe")

for text in transcribe(files):
    print(text)
```

<img width="769" alt="image" src="https://github.com/neuml/txtai/assets/20000097/1ac61759-ba9a-4575-bf93-ceda3534c7a5">

**Comment by davidmezzetti** [comment]
Thanks for confirming. I'll keep this issue open and add an argument to disable automatic translation.
