### ISSUE TITLE
Integration with Azure Open AI model for embedding and text generation ?

### ISSUE THREAD

**Issue by mrhimanshu** [neuml/txtai#595]
Is there any way by which we can integrate azure open ai embedding and text generation part ? Any wrapper around to add it as path ?

**Comment by davidmezzetti** [comment]
Hello,

Yes this is possible. See the links below for more.

- [Running at scale with txtai](https://medium.com/neuml/running-at-scale-with-txtai-71196cdd99f9)
- [External vectorization](https://neuml.hashnode.dev/customize-your-own-embeddings-database#heading-external-vectorization)
- [External LLMs](https://neuml.hashnode.dev/prompt-driven-search-with-llms#heading-external-api-integration)

**Comment by davidmezzetti** [comment]
In addition to the resources mentioned above, there is also now an integration with [LiteLLM](https://github.com/BerriAI/litellm).

See these links for more:

- [Integrate LLM Frameworks](https://neuml.hashnode.dev/integrate-llm-frameworks)
- [Azure Provider](https://docs.litellm.ai/docs/providers/azure)
