### ISSUE TITLE
fasttext pybind11 wheel failure

### ISSUE THREAD

**Issue by JeremyBickel** [neuml/txtai#597]
I ran into this problem trying to install extra packages (eg. txtai[all]). It requires and tries to build fasttext, but it fails due to not finding pybind11. I have pybind11. I have fasttext, correct version and everything, but it insists on trying to build it and it fails.

For reference in case someone else runs into this, here's how I fixed it. I found the wheel file and edited the metadata to exclude fasttext.

Find the pip cache directory> "pip cache dir"
Go there, and create a temp dir> "mkdir a"
Change to that directory> "cd a"
Unzip the wheel> "unzip ../txtai-6.1.0-py3-none-any.whl"
Rename the wheel file in case something goes wrong> "mv ../txtai-6.1.0-py3-none-any.whl ../txtai-6.1.0-py3-none-any.whl.bak"
Go into the .dist-info directory in the unzipped directory structure> "cd txtai-6.1.0.dist-info"
Edit the METADATA file> "vim METADATA" (or nano or any text editor)
Find all instances of fasttext (I found 4), and delete the whole line wherever you find it.
Save the file.
Back in the temp directory, repack the zip file into a wheel> "zip -r ../txtai-6.1.0-py3-none-any.whl ."
Install the wheel directly> "pip install ../txtai-6.1.0-py3-none-any.whl"

Will someone verify that this is a workable procedure?

**Comment by davidmezzetti** [comment]
Do you have a C++ compiler installed? That is typically the reason fasttext installs fail.

I would never recommend an approach like this. The root cause should be addressed and a fix put into the project.

**Comment by JeremyBickel** [comment]
Thanks, @davidmezzetti . I know this is a total hack, and I very much desire clean corners boxing in all the code everywhere, but I had to do something, and I find that I'm nowhere near technical enough. So, this is what we have. And, if it helps someone like me, I'll call it worthwhile to report *some* workaround - just for practical purposes, you know?

Do you think there's a root cause to fix? I have gcc installed. Except for an upstream issue with fasttext, and they stopped dev a long time ago, I don't know any other solution.

**Comment by davidmezzetti** [comment]
What version of Python are you using?

**Comment by davidmezzetti** [comment]
This issue might be relevant: https://github.com/neuml/txtai/issues/572

**Comment by JeremyBickel** [comment]
Python == 3.11.6

I saw this solution in the fasttext repo, but I don't know how to apply it for this wheel. I can install fasttext with apt, but the txtai wheel tries to compile it anyway. If there's a clean solution, I'd think it was in getting the wheel to stop trying to compile things that already exist in the system.
