### ISSUE TITLE
PubMed version of the txtai-wikipedia db?

### ISSUE THREAD

**Issue by davies-w** [neuml/txtai#598]
I raised this here https://huggingface.co/NeuML/txtai-wikipedia/discussions/1, but as this is the GitHub home of NeuML, I figured I'd x-post the question here in case it gets a faster response :)

This wikipedia embedding database is great! I've used it for testing Q&A, but I'm now wondering if there is an equivalent, but for PubMed abstracts. I've seen you have PubMedBert embeddings, but that's not the same as a pre-indexed set of retrievable docs.
I've scoured the internet thinking someone would have done this as a service to humanity, but apparently not. Given how many people have processed PubMed in various forms for LLMs, is there a legal or logistical reason why this hasn't been done yet?

**Comment by davidmezzetti** [comment]
Thank you for the kind words on txtai-wikipedia.

Building a publicly available database like txtai-wikipedia for PubMed hasn't been a priority from my standpoint. So it's not something I've researched to be able to speak knowledgeably enough on.

**Comment by davies-w** [comment]
Oh no worries, I suspect if something had been done with PubMed you'd have seen it, at least more than I would have. I had a dig around with Google, but nothing surfaced. Appreciate the response!
