### ISSUE TITLE
txtai as a server deployment

### ISSUE THREAD

**Issue by TensorBlast** [neuml/txtai#602]
Hi
I have attempted to go through the API documentation but found it severely lacking.
I have tried myself to deploy txtai as a FastAPI server which works, and am able to call transform endpoint to get embeddings but am at a loss on how to proceed from there.

There are bindings for Java, Go, Javascript etc but I don't see a python client application. Apologies if the question is too rudimentary but how do I go about consuming the FastAPI endpoint with Python for the following steps:

1. Add text (and associated embeddings) to the datastore
2.  How to get embeddings given some text
3. Perform ANN search/ HNSW search using text input
4. Perform CRUD operations in order to update/upsert documents etc.

Also what is the concept of Index here? I read it is created AFTER adding documents. Is this something like the SQL database indexes which are used to speed up retrieval etc?

**Comment by davidmezzetti** [comment]
Please see this related Reddit thread: https://www.reddit.com/r/LocalLLaMA/comments/15o5fqf/comment/kbmfiql/

**Comment by davidmezzetti** [comment]
Closing this issue. If there are further questions, please re-open or open a new issue.
