### ISSUE TITLE
Image Search with Subindices

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#606]
Could you provide an example of this image search can used with other data using subindices? 
I get this error when I try to upsert the vector-database with image data.

```
embeddings = Embeddings(
    content=True,
    defaults=False,

    indexes={
        "text-data": {
            "tokenize": True,
            "path": "sentence-transformers/multi-qa-mpnet-base-dot-v1",
            "columns": {
                "text": "text-data"
            },

        "image":{
            "tokenize": True,
            "method": "sentence-transformers",
            "path": "sentence-transformers/clip-ViT-B-32",
            "objects": "image",
            "columns": {
                "object": "image"
            }
        }
    })
```

```
embeddings.insert([(uid, {"object": image, "format": image.format, "width": image.width, "height": image.height}}, image_file)])
```

```
TypeError: Object of type JpegImageFile is not JSON serializable
```

https://github.com/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb

**Comment by vnguye65** [comment]
@davidmezzetti  This code seems to work without the "columns" parameter in the Embedding config

**Comment by davidmezzetti** [comment]
Hello, that is correct. Since you are using the default object field name of `object`. If you add the columns config back in for the subindex, it would have to look like this:

```json
"columns": {
  "object": "object"
}
```

**Comment by vnguye65** [comment]
Another question I have is is there a way to weigh the subindexes when during combined search?

**Comment by davidmezzetti** [comment]
Did you try?

```python
embeddings.search('select object, score from txtai where similar("machine learning", "image")')
```

or 

```python
embeddings.search('select object, score from txtai where similar("machine learning")', index="image")
```

**Comment by davidmezzetti** [comment]
I will try to find time to come up with an example that does what you want to do with the appropriate configuration. I think some of the configuration you have could be throwing something off.

**Comment by vnguye65** [comment]
With the current configuration, I noticed that it only calculates similarity using the `text` field in `data`

**Comment by davidmezzetti** [comment]
The following code should give you what you're looking for.

```python
from PIL import Image

from txtai import Embeddings

embeddings = Embeddings(
    content=True,
    objects="image",
    defaults=False,
    indexes={
        "text-data": {
            "columns": {
                "text": "body",
                "object": "content"
            }
        },
        "image":{
            "method": "sentence-transformers",
            "path": "sentence-transformers/clip-ViT-B-32",
            "columns": {
                "text": "image-text"
            }
        }
    }
)

embeddings.index([{"object": Image.open("books.jpg")}, {"body": "machine learning"}])
```

And supports the following queries.

```python
embeddings.search("select id, score from txtai where similar(:x, :y)", parameters={"x": "books", "y": "text-data"})
# [{'id': '1', 'score': 0.3759748339653015}]

embeddings.search("select id, score from txtai where similar(:x, :y)", parameters={"x": "books", "y": "image"})
# [{'id': '0', 'score': 0.2725779414176941}]

embeddings.search("select id, object, score from txtai where similar(:x, :y)", parameters={"x": Image.open("books.jpg"), "y": "image"})
# [{'id': '0', 'object': <Image>, 'score': 0.9999999403953552}]

embeddings.search("select id, score from txtai where similar(:x, :y) or similar(:x, :z)", parameters={"x": "books", "y": "image", "z": "text-data"})
# [{'id': '1', 'score': 0.3759748339653015}, {'id': '0', 'score': 0.2725779414176941}]

embeddings.search("select id, score from txtai where similar(:x, :y) and similar(:x, :z)", parameters={"x": "books", "y": "image", "z": "text-data"})
# []
```

The tricky thing is that the CLIP model encodes both text and images. So the config needs to be setup to skip text records. Note how both indexes have non-standard names for the text column.

**Comment by davidmezzetti** [comment]
Closing this issue. If there are further questions, please re-open or open a new issue.

**Comment by davidmezzetti** [comment]
It looks like in dev you're using Python directly and prod is using the API?

**Comment by vnguye65** [comment]
Yes. We're using the API in prod.

**Comment by vnguye65** [comment]
@davidmezzetti Do you have insights into why it's throwing an error with API but working perfectly when calling `txtai.app.Application` in Python? Any information you have would be greatly appreciated.

**Comment by davidmezzetti** [comment]
The API does not currently support multi-part form submissions for embeddings inputs. I will try to work on an example to demonstrate how to do that but it will involve adding a custom API endpoint. This article has an example of that.

https://neuml.hashnode.dev/custom-api-endpoints

**Comment by vnguye65** [comment]
@davidmezzetti  Do you have any updates on this issue?

**Comment by davidmezzetti** [comment]
Sending binary data through the API isn't currently supported. It's something I want to add and showing how to do it in the meantime with a custom endpoint is on my list.

**Comment by davidmezzetti** [comment]
Closing here and tracking this in #606.
