### ISSUE TITLE
Pipeline requests

### ISSUE THREAD

**Issue by ranjancse26** [neuml/txtai#616]
Is it possible to have the sentiment analysis, emotion analysis, topic detection, keyword extraction, aspect analysis etc. as part of the txtai pipeline?

**Comment by davidmezzetti** [comment]
Hello. I'm sure there are models from the Hugging Face Hub for many of these tasks and most appear to be text classification tasks. In what way would this be different than using the `Labels` pipeline with one of these models to accomplish these tasks?

**Comment by ranjancse26** [comment]
Yes, there are quite a few great models from HF. However, I was looking for an easy to use integration with the txtai. The labels pipeline is doing the zeroshot technique and is not solving the problems of other textual data mining tasks.

**Comment by davidmezzetti** [comment]
If you use `Labels(dynamic=False)` then the pipeline can load a standard text classification model. This probably could be better documented but it's [mentioned here](https://neuml.github.io/txtai/pipeline/text/labels/#txtai.pipeline.text.labels.Labels.__init__).

**Comment by davidmezzetti** [comment]
Closing this as I believe the question is answered. If there are further questions, please re-open or open a new issue.
