### ISSUE TITLE
[Python 3.9, Mac OS] Code hangs while building embedding index

### ISSUE THREAD

**Issue by hardikudeshi** [neuml/txtai#62]
Minimal example below. I suspect something weird is happening to multithreading, but was not able to confirm or find a resolution.

```
Python version - 3.9.1
OS - Mac Big Sur
```

```python
import os
import tempfile
import pandas as pd


from txtai.tokenizer import Tokenizer
from txtai.vectors import WordVectors
from txtai.embeddings import Embeddings

# generate random data
random_array = ["a" + pd.util.testing.rands_array(3, 2) for i in range(100)]
df = pd.DataFrame(random_array, columns=list("AB"))


with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as output:
    tokens = output.name

    for row in range(df.shape[0]):
        output.write(" ".join(Tokenizer.tokenize(df.iloc[row, 0])) + "\n")

WordVectors.build(tokens, 10, 1, "search-data")

os.remove(tokens)

def stream():
    for row in range(df.shape[0]):
        uid = row
        tokens = Tokenizer.tokenize(df.iloc[row, 0])
        document = (uid, tokens, None)
        yield document

embeddings = Embeddings({"path": "search-data.magnitude"})

# Code hangs here
embeddings.index(stream())
```

**Comment by davidmezzetti** [comment]
Thank you for reporting this  issue!

I was able to run the code above on a Linux system for Python 3.7-3.9 without issue.

I wonder if Faiss is the issue here. Did you run `brew install libomp`? Faiss was also recently upgraded to 1.7.0. 

Couple tests to try if libomp is installed:

- Install Faiss 1.6.3
- Change the ANN backend:

```python
# Also can try annoy
embeddings = Embeddings({"path": "search-data.magnitude", "backend": "hnsw"})
```

**Comment by hardikudeshi** [comment]
Backend doesn't seem to be an issue. I tried with `"backend":"hnsw"` - it doesn't work. The root cause seems to be `Pool` functionality in the following code snippet.

```python
with Pool(os.cpu_count(), initializer=create, initargs=args) as pool:
    with tempfile.NamedTemporaryFile(mode="wb", suffix=".npy", delete=False) as output:
        stream = output.name
        for uid, embedding in pool.imap(transform, documents):
            if not dimensions:
                # Set number of dimensions for embeddings
                dimensions = embedding.shape[0]

            ids.append(uid)
            pickle.dump(embedding, output)

return (ids, dimensions, stream)
```

When I replaced this part of the code by `map` (without Pool), the code ran through.

Seems to be an upstream issue. Can you think of any workarounds?

**Comment by davidmezzetti** [comment]
Thank you for following up.

The current GitHub Actions script runs Python 3.6 + macOS Catalina 10.15. Could you try installing Python 3.8 to see if the issue persists? 

Alternatively, maybe setting the start method for multiprocessing - https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods?

I see some notes there regarding macOS with Python 3.8+

It also wouldn't be that difficult to have a config parameter that disables multiprocessing.

**Comment by hardikudeshi** [comment]
It didn't work for Python 3.8.5 as well. It works for Python 3.6.12.

Having a config param controlling multiprocessing would be ideal, it could facilitate small experiments before scaling up.

Thanks for the pointers.

**Comment by davidmezzetti** [comment]
If you're still tuned in, just committed a possible fix to address this issue. If you add "parallel": false as a config parameter it will build word vectors serially. I haven't been able to reproduce this issue, so if you're able to try from the main branch, it would be appreciated.

**Comment by hardikudeshi** [comment]
Thanks David, this fix works.

**Comment by davidmezzetti** [comment]
Great, thank you for confirming!

**Comment by heijligers** [comment]
I'm getting a segmentation fault in libomp on macos M1 python 3.11 and 3.9
Could this still be relevant?
