### ISSUE TITLE
Error in 52_Build_RAG_pipelines_with_txtai.ipynb

### ISSUE THREAD

**Issue by askppp** [neuml/txtai#620]
Hi, 

thank you very much for this repo. I'm enjoying my time learning with it :)). 

I was trying to follow the colab of building RAG and i came across this error. I wanted only to pay your attention to it because it's used in the docs. 

![Error Build_RAG_pipelines](https://github.com/neuml/txtai/assets/102218389/09aafc07-fff1-4fb2-970c-da279b5a25df)

Thanks.

**Comment by davidmezzetti** [comment]
Thank you for reporting this bug. It's possible LiteLLM changed the API and this broke txtai's LLM pipeline.

**Comment by davidmezzetti** [comment]
Thank you for letting me know, this bug has been fixed!

**Comment by askppp** [comment]
Sorry, but i'm still getting an error. I tried some solutions but still didn't work.

![Error](https://github.com/neuml/txtai/assets/102218389/6f20ecdf-1db2-4ea7-b51f-d0258aa64028)

**Comment by davidmezzetti** [comment]
This can happen in some cases with Colab when an installed package is updated. The best thing to do is to restart the kernel and run all again. 

See the FAQ for more on this: https://neuml.github.io/txtai/faq/#common-issues
