### ISSUE TITLE
Return count of all matching records in `embeddings.search`

### ISSUE THREAD

**Issue by vnguye65** [neuml/txtai#621]
Is there a way to return all matching records using `embeddings.search` since the number of rows returned seems to be capped at 30. We're looking to get a count of how many texts satisfy a condition. 
``` query = SELECT *, COUNT(*) OVER () AS total_sources from txtai WHERE  condition``` always returns 30.

**Comment by davidmezzetti** [comment]
Hello,

This is a tricky one as txtai is integrates external indexes for vector search. This requires a full index scan to pull back a result like this, so by default it doesn't do this. 

If you want something like this, you'd need to set a LIMIT. For example,

```python
query = SELECT *, COUNT(*) OVER () AS total_sources from txtai WHERE  condition LIMIT 99999999
```
