### ISSUE TITLE
QUESTION. Debugging, tracing, observability?

### ISSUE THREAD

**Issue by 4l1fe** [neuml/txtai#626]
Hey, i like how minimalistic txtai is, a way better to get started with then competitors.

Thinking about debbuging, i don't find txtai's solution such as [langchain debugging](https://python.langchain.com/docs/guides/debugging) or [llamaindex tracing](https://docs.llamaindex.ai/en/stable/understanding/tracing_and_debugging/tracing_and_debugging.html) have.

Does txtai provide with something like advanced logging or whatever to see all the steps in Workflow, Pipeline, etc. ?

**Comment by davidmezzetti** [comment]
Debugging through txtai would be more similar to llamaindex using standard Python logging. There is some logging built in but nothing too verbose. It's a fair point to consider though, thank you for bringing up the idea.

**Comment by 4l1fe** [comment]
Ok, thank you.

**Comment by davidmezzetti** [comment]
You're welcome. If you end up using txtai more and have specific areas where you think more logging would help, please let me know.

**Comment by yukiman76** [comment]
How about adding Arize Phoenix ?

**Comment by davidmezzetti** [comment]
Just closing the loop on this question. Unfortunately, the license for Arize Phoenix isn't compatible with txtai.
