### ISSUE TITLE
Unnecessary http requests `HEAD`.

### ISSUE THREAD

**Issue by 4l1fe** [neuml/txtai#635]
With logging being `DEBUG`, i see that txtai send requests every time i initialize `LLM()` class.

```
DEBUG 2024-01-09 23:58:56,704 Starting new HTTPS connection (1): huggingface.co:443
DEBUG 2024-01-09 23:58:57,075 https://huggingface.co:443 "HEAD /TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf HTTP/1.1" 302 0
```

I have TinyLlama downloaded and would not like to block a service for a short while by them.

Actually i have two questions here:
1. How to disable this `HEAD` request?
2. How to manually download a model, should i do it without txtai or with?

**Comment by davidmezzetti** [comment]
Hello,

These requests are coming from the `huggingface_hub` library. It's checking to see if a newer version of the file exists. They have an offline mode that disables this - https://huggingface.co/docs/huggingface_hub/v0.20.2/en/package_reference/environment_variables#hfhuboffline

Couple different options for manually downloading.

- Run the code once normally and then set the offline parameter
- Manually download the files through the web interface. For example - https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/blob/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
- Run `wget -O tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf?download=true`

If you manually download the GGUF file and put it in a local directory, the `huggingface_hub` library is bypassed and the `llm` pipeline directly loads the file with llama-cpp-python.

**Comment by 4l1fe** [comment]
Nice, thx. I supposed that as txtai wraps `huggingface.pipeline` the issue could arise from it and you confirmed. Appreciate it. 

Is a path to a local model file the `LLM.path` argument? It can be a file system path?

**Comment by davidmezzetti** [comment]
That's correct. It first runs `os.path.exists` on the path and will use that if it does. Otherwise, it falls back to using the `huggingface_hub` library.

**Comment by 4l1fe** [comment]
> That's correct. It first runs `os.path.exists` on the path and will use that if it does. Otherwise, it falls back to using the `huggingface_hub` library.

Great, thx. I prefer to predownload models and then explicitly load them into RAM to keep my service controlable.

By the way, don't you know if it's alright just to delete a model variable, instance to release memory?

Let's say the concept is:
```
class Loader:
    def load(self, model):
        self.llm = LLM(model)
    
    def unload(self):
        del self.llm
```

**Comment by davidmezzetti** [comment]
You could also set `self.llm = None`.

**Comment by 4l1fe** [comment]
Thx for help!
