### ISSUE TITLE
Check for Duplicates

### ISSUE THREAD

**Issue by fakerybakery** [neuml/txtai#638]
Hi,
Is it possible to check for duplicates?
For example, in [this example](https://github.com/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb), can I not insert an item if another item with the same caption already exists?
Thanks!

**Comment by davidmezzetti** [comment]
The default mode of an upsert operation is to overwrite duplicates with the new version. If you'd like to reject the new records, the best thing to do would be to add a query before the upsert checking which ids already exist and not loading those.

**Comment by fakerybakery** [comment]
Nice, thank you!
