### ISSUE TITLE
Modify pipeline to accept GPU device id

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#64]
Currently, pipelines have a GPU flag to enable/disable. This parameter should also support integer device numbers. This will allow handling multi-GPU systems.

**Comment by aquibjaved** [comment]
Hi @davidmezzetti,
I would like to try this. shall I create a draft PR?

**Comment by davidmezzetti** [comment]
Thank you, happy to take PRs!

For this one, it would be ideal to re-use the gpu flag as follows:

gpu = False translates to device = -1
gpu = True translates to device = 0
gpu = <int> translates to device = (int value stored in gpu)

**Comment by davidmezzetti** [comment]
Not sure if this was still being work but a major refactor is in the works that added this feature. Thank you for volunteering regardless!
