### ISSUE TITLE
How does this database differ from other vector databases?

### ISSUE THREAD

**Issue by kleenkanteen** [neuml/txtai#655]
The ones I read about online if I search "vector databases" include Weaviate, Pinecone, Zilliz, and Qdrant mainly. This article series is the best deep dive I've seen comparing them all: https://thedataquarry.com/posts/vector-db-1/

I see you've put in a lot of work in txtai and I had it saved for a while but never got around to using it (didn't build any LLM applications either). How does it differ from those? There are so many options and it gives me decision fatigue because I read a lot about them. At the end of the day I want one with the easiest DX and a team behind the product. You have tons of nice examples using txtai but only you are building it. Why should I use txtai over Weaviate or Qdrant? According to the article I linked above, these 2 have the best DX.

**Comment by davidmezzetti** [comment]
This page gives more on "Why txtai?" https://neuml.github.io/txtai/why/

A great resource to read is this Vector DB Comparison site https://vdbs.superlinked.com/. It gives a nice breakdown by feature.

I'd recommend picking an option you're comfortable with. If you like the options you mentioned, give it a try. If after using it for a while, you don't like it, try another.

The only DX that matters is your own or your teams. I wouldn't put too much stock in what others say.

**Comment by seoeaa** [comment]
> The ones I read about online if I search "vector databases" include Weaviate, Pinecone, Zilliz, and Qdrant mainly. This article series is the best deep dive I've seen comparing them all: https://thedataquarry.com/posts/vector-db-1/
> 
> I see you've put in a lot of work in txtai and I had it saved for a while but never got around to using it (didn't build any LLM applications either). How does it differ from those? There are so many options and it gives me decision fatigue because I read a lot about them. At the end of the day I want one with the easiest DX and a team behind the product. You have tons of nice examples using txtai but only you are building it. Why should I use txtai over Weaviate or Qdrant? According to the article I linked above, these 2 have the best DX.

https://vdbs.superlinked.com/?utm_source=twitterads&utm_medium=cpc&utm_campaign=twitter_keywords_v1&utm_id=twitter_keywords_v1&utm_term=vectordb+embeddings&twclid=24khsrx2ufsw2h24ccvsxkie7n

**Comment by davidmezzetti** [comment]
Closing this issue. Please re-open or open a new issue if there are further questions.
