### ISSUE TITLE
txtai[pipeline] fasttext build fails miserably

### ISSUE THREAD

**Issue by scrwghub** [neuml/txtai#716]
txtai[pipeline-text] cannot be installed. Build of fasttext fails in such a diversity and depth of ways that this issue report is too small to contain.

I only wanted to split my paragraphs. Seems unreasonably punitive. 

Looking into it comes down to wheel, adventurous runtime behaviour changes in pip, ignored issues at the fasttext repo, etc. At the fasttext repo they seem to believe this was fixed in 2019. 

Anyway seems like a whole lot of rot in this dependency. I'll split my own paragraphs for now, and I'm sure you'll find the best way forward.

**Comment by davidmezzetti** [comment]
First off, this title gave me a chuckle, so thank you for that 😂

I believe someone (perhaps I will have to do it) will need to push a new version of fastText to PyPI. There are numerous fixes in the GitHub project for later Python version that haven't made it to PyPI.

What happens if you run:

```
pip install git+https://github.com/facebookresearch/fastText
```

**Comment by scrwghub** [comment]
I'm glad you had a chuckle :)

As you suggested, installing git fasttext then allows a clean installation of txtai[pipeline]. Thank you for that. 

Just one more question, is there a way to trim down the dependencies? By simply installing txtai I get 5.2gb virtual env. Since I am using pure cpu functionality in txtai, is there a way I could cut down some of it like nvidia stuff?

Thank you and you can close this when you want.

**Comment by davidmezzetti** [comment]
Just mentioned some ideas over on this issue: https://github.com/neuml/txtai/issues/715
