### ISSUE TITLE
Can't run example 55_Generate_knowledge_with_Semantic_Graphs_and_RAG.ipynb

### ISSUE THREAD

**Issue by kellytsorb** [neuml/txtai#721]
Hello,
I want to run the example with the Wikipedia dataset to understand the query = """
SELECT id, text FROM txtai
order by percentile desc
LIMIT 100000
""" 
because when I run the code with my embeddings the query works as string and takes it as a sentence and searches through my financial texts. As a result the answers are wrong because it shows results relayted to id, text, txtai and not for example earning management, or financial risk. Also, the other issue is that the dataset of wikipedia isn't loading as shown in the screenshot below everything with the code it seems fine but it doesn't load. Is there any ideas of what it's happening?
Thank you in advance!
<img width="554" alt="Screenshot 2024-05-23 at 12 56 38 PM" src="https://github.com/neuml/txtai/assets/77836075/c2413bce-5532-4f8e-abd2-feb76f638228">

**Comment by davidmezzetti** [comment]
Hello and thank you for writing this up.

From the sound of it, I'd guess that the new Embeddings being created doesn't have `content=True`. Without setting content to True, all queries are considered text queries.

I'd retry downloading the wikipedia index. It seems like you were running into a Hugging Face Hub issue.

**Comment by kellytsorb** [comment]
Hello thank you for your response.
I changed the `content=True` and it works with my embeddings.
@davidmezzetti

**Comment by davidmezzetti** [comment]
Excellent, glad it worked.
