### ISSUE TITLE
Example code (10_Extract_text_from_documents.ipynb) does not work: No module named 'txtai.pipeline'; 'txtai' is not a package

### ISSUE THREAD

**Issue by awaescher** [neuml/txtai#751]
Just like #646 I cannot create an instance of `Textractor`.

The following code from [examples/10_Extract_text_from_documents.ipynb](https://github.com/neuml/txtai/blob/master/examples/10_Extract_text_from_documents.ipynb) ...

```python
from txtai.pipeline import Textractor
textractor = Textractor()
```

... won't run:

```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[30], line 7
      4 from txtai.pipeline import Textractor
      6 # Create textractor model
----> 7 textractor = Textractor()

File ~/.local/lib/python3.11/site-packages/txtai/pipeline/data/textractor.py:32, in Textractor.__init__(self, sentences, lines, paragraphs, minlength, join, tika, sections, headers)
     30 def __init__(self, sentences=False, lines=False, paragraphs=False, minlength=None, join=False, tika=True, sections=False, headers=None):
     31     if not TIKA:
---> 32         raise ImportError('Textractor pipeline is not available - install "pipeline" extra to enable')
     34     super().__init__(sentences, lines, paragraphs, minlength, join, sections)
     36     # Determine if Apache Tika (default if Java is available) or Beautiful Soup should be used
     37     # Beautiful Soup only supports HTML, Tika supports a wide variety of file formats.

ImportError: Textractor pipeline is not available - install "pipeline" extra to enable
```

Checking the txtai code, I found that this error occurs if `TIKA` is set to `false` [here](https://github.com/neuml/txtai/blob/3e978981d9f6c40ad3bfa2358552264c87898f02/src/python/txtai/pipeline/data/textractor.py#L32).

This seems to only be able if one of these two lines fail:
![image](https://github.com/user-attachments/assets/13d55982-367c-465f-a899-2ac10591c60d)

So I added them to my Jupiter notebook as well and they worked but the txtai error stays:

![image](https://github.com/user-attachments/assets/c3b495e3-1c69-4828-a235-8e969867833c)

---

I am running my Jupiter notebook within a DevContainer (`mcr.microsoft.com/vscode/devcontainers/python:3.11-bullseye`) in Visual Studio Code on WSL on Windows.

**Comment by davidmezzetti** [comment]
Hello. Did you try escaping the pip install line as suggested in the FAQ?

https://neuml.github.io/txtai/faq/

**Issue**

Error installing optional/extra dependencies such as pipeline

**Solution**

The default MacOS shell (zsh) and Windows PowerShell require escaping square brackets

```
pip install 'txtai[pipeline]'
```

**Comment by davidmezzetti** [comment]
You can try installing the dependencies directory. 

```
pip install beautifulsoup4 tika
```

**Comment by awaescher** [comment]
```
vscode ➜ /workspace $ pip install beautifulsoup4 tika
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/site-packages (4.12.3)
Requirement already satisfied: tika in /home/vscode/.local/lib/python3.11/site-packages (2.6.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/site-packages (from tika) (71.1.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from tika) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests->tika) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests->tika) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests->tika) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests->tika) (2024.7.4)
```

**Comment by awaescher** [comment]
> Defaulting to user installation because normal site-packages is not writeable
🤔
(really appreciating your help btw)

**Comment by davidmezzetti** [comment]
What happens if you run this in your notebook?

```python
from bs4 import BeautifulSoup, NavigableString
from tika import detector, parser
```

**Comment by awaescher** [comment]
It's working, just tried it again.

![image](https://github.com/user-attachments/assets/08ab5309-977e-4b32-9259-07c39bc81755)

But you can see these lines were part of the code in the first screenshot, too.

**Comment by davidmezzetti** [comment]
If you restart the notebook and run again? I don't really know, you see the code there is no way that variable is set to False otherwise.

**Comment by awaescher** [comment]
Well, damn! I can't believe it was so simple and the most basic IT kind of making things work.
Aw man, sorry for your time. Throwing it all away and trying again suddenly worked.

![image](https://github.com/user-attachments/assets/35510ddc-f67f-4055-880a-510aa1a3fc0e)

I should have tried this before ... thanks once again!

**Comment by davidmezzetti** [comment]
No problem, happy to help.
