### ISSUE TITLE
llama.cpp / llamafile api  server with api_base ?

### ISSUE THREAD

**Issue by quantumalchemy** [neuml/txtai#759]
is it possible to use this setup:
I have an external llama.cpp  (or llamafile) server  running in a docker co nt.  -> http://localhost:8000/v1
can I use litellm? or openai compatible ?
llm = LLM(path="myLLM", api_base="http://localhost:8001/v1", api_key="None")
will this work?

**Comment by davidmezzetti** [comment]
Yes this is possible. I believe you'd just need to prefix the path with `openai`.

```python
 llm = LLM(path="openai/myLLM", api_base="http://localhost:8001/v1", api_key="None")
```
