### ISSUE TITLE
Local ollama embeddings not working but LLM with ollama does

### ISSUE THREAD

**Issue by ferpuyol** [neuml/txtai#762]
I'm not sure if I'm doing it correctly but using the following example:

```
data = [
        "US tops 5 million confirmed virus cases",
        "Canada's last fully intact ice shelf has suddenly collapsed, forming a Manhattan-sized iceberg",
        "Beijing mobilises invasion craft along coast as Taiwan tensions escalate",
        "The National Park Service warns against sacrificing slower friends in a bear attack",
        "Maine man wins $1M from $25 lottery ticket",
        "Make huge profits without work, earn up to $100,000 a day"
        ]
        
        # Vector store with embeddings via local Ollama server
        embeddings = Embeddings(path="ollama/all-minilm:latest", content=True, api_base="http://192.168.100.25:11434")
        embeddings.index(data)
    
        # LLM via local Ollama server
        llm = LLM(path="ollama/gemma2:2b")
        
        # Question and context
        question = "funny story"
        context = "\n".join(x["text"] for x in embeddings.search(question))
        
        # RAG
        llm([
            {"role": "system", 
            "content": "You are a friendly assistant. You answer questions from users."},
            {"role": "user", 
            "content": f"""
            Answer the following question using only the context below. Only include information
            specifically discussed.
            question: {question}
            context: {context}
            """}
        ])
```

can't get it to work. I have tried with api_base, without api_base, with "ollama/all-minilm:latest", with "ollama/all-minilm" and I always get an error on the line:
 embeddings.index(data)
The error is:

```
192.168.100.25 - - [13/Aug/2024 21:54:16] "POST /test HTTP/1.1" 202 -
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/newLiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
Provider List: https://docs.litellm.ai/docs/providers
Error during upload: <class 'litellm.exceptions.APIConnectionError'> index.py 232
```
verbose=True doesn't give me more info.
However, when using txtai LLM() with Ollama I can connect and get responses. Ollama server is working fine

Thanks!

**Comment by davidmezzetti** [comment]
Hello. Can you try this:

```python
        # Vector store with embeddings via local Ollama server
        embeddings = Embeddings(
          path="ollama/all-minilm:latest",
          content=True, 
          vectors={"api_base": "http://192.168.100.25:11434"}
        )
        embeddings.index(data)
```

Reference: https://neuml.github.io/txtai/embeddings/configuration/vectors/#vectors_1

**Comment by ferpuyol** [comment]
Thanks for your quick answer. I tried your suggestion but give me same error on same line: embeddings.index(data)
The script is running on ubuntu 24.04, all required python libs installed. litellm ver 1.43.7, txtai 7.3.0

**Comment by davidmezzetti** [comment]
Did you pull the image via `ollama pull`? I know that can sometimes cause issues.

**Comment by ferpuyol** [comment]
That's right, I downloaded it with pull.
I just tried with gemma2:2b downloaded with "run" and I can't create the index either. Same mistake.
My goal is to leverage the GPU for the index process. But if I can do it with litellm it would be a workaround.
If you know a way to do it I would appreciate it. I'm going to try starting everything from scratch in a few hours.
Thanks!!

**Comment by davidmezzetti** [comment]
Perhaps there is an issue with the setup. Are you running Ollama through Docker and forwarding port 11434?

**Comment by ferpuyol** [comment]
I'm sorry but I must correct myself. After removing the code from a try catch block the error changed to:

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
Provider List: https://docs.litellm.ai/docs/providers
Traceback (most recent call last):
  File "/home/ai/venvs/rag1/lib/python3.12/site-packages/litellm/main.py", line 3522, in embedding
    response = ollama_embeddings_fn(  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/venvs/rag1/lib/python3.12/site-packages/litellm/llms/ollama.py", line 602, in ollama_embeddings
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ai/venvs/rag1/lib/python3.12/site-packages/litellm/llms/ollama.py", line 542, in ollama_aembeddings
    logging_obj.pre_call(
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/venvs/rag1/lib/python3.12/site-packages/pydantic/main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'EmbeddingResponse' object has no attribute 'pre_call'
```
and goes on...

Then i reinstalled all python env on another PC with ubuntu running ollama and changed all api_base to localhost

Using embeddings = Embeddings(path="sentence-transformers/nli-mpnet-base-v2") works Ok
Using embeddings = Embeddings(path="ollama/all-minilm",method="litellm",api_base= "http://localhost:11434") or
embeddings = Embeddings(path="ollama/all-minilm",method="litellm",vectors={"api_base": "http://localhost:11434"}) throws same error "object has no attribute 'pre_call'"

Ollama is running as a local service, not dockerized,  and llm querys using txtai with ollama works fine

**Comment by davidmezzetti** [comment]
You might be running into this: https://github.com/BerriAI/litellm/pull/5116

I suggest chiming in on that thread.

**Comment by krrishdholakia** [comment]
just fixed on our end!

**Comment by davidmezzetti** [comment]
Thank you for the upstream fix! Looks like this should be fixed with the next LiteLLM release (or you can install the latest source release from GitHub).

**Comment by davidmezzetti** [comment]
Looks like this is now in the latest version of litellm, closing.
