### ISSUE TITLE
Cannot import Textractor, No module named 'txtai.pipeline'

### ISSUE THREAD

**Issue by republic-of-la** [neuml/txtai#764]
I get an error 
"ModuleNotFoundError: No module named 'txtai.pipeline'"

when importing from txtai.pipeline import Textractor from this example 

https://colab.research.google.com/github/neuml/txtai/blob/master/examples/10_Extract_text_from_documents.ipynb

**Comment by davidmezzetti** [comment]
Can you get the latest copy of the notebook and try again? There was a NLTK issue today that likely caused this.

https://github.com/neuml/txtai/issues/760

**Comment by republic-of-la** [comment]
hi there david, really love this extractor and it worked perfectly yesterday. 

today it seems there is an issue with this  "import ImportError: Textractor pipeline is not available "


error message: ------------------------------------------------------------------------------------------

[/usr/local/lib/python3.10/dist-packages/txtai/pipeline/data/textractor.py](https://localhost:8080/#) in __init__(self, sentences, lines, paragraphs, minlength, join, tika, sections, headers)
     30 
     31     def __init__(self, sentences=False, lines=False, paragraphs=False, minlength=None, join=False, tika=True, sections=False, headers=None):
---> 32         if not TIKA:
     33             raise ImportError('Textractor pipeline is not available - install "pipeline" extra to enable')
     34 

ImportError: Textractor pipeline is not available - install "pipeline" extra to enable
---------------------------------------------------------------------------------------------------------

**Comment by republic-of-la** [comment]
hi there, given your suggestion, i applied a previous version of nltk and it worked

!pip install nltk==3.8.0
import nltk
nltk.download('punkt')

**Comment by davidmezzetti** [comment]
Glad to hear it!
