### ISSUE TITLE
Feature Request: Callback function to get progress of index process

### ISSUE THREAD

**Issue by ferpuyol** [neuml/txtai#767]
Looking for a callback function in embeddings.index to get the progress of large data sets.

So far I did it by adding a callback function in embeddings.index and passing the function to eight functions in:
embeddings/base.py,
embeddings/index/transform.py,
vectors/base.py,
vectors/hugghingface.py,
models/pooling/base.py

I know, it looks ugly.
I already saw the solution with tqdm but I want to get the progress and send it to the front so I did it my way.
I think there must be a better way, and probably a persistent one to updates, but for now it works. I'm sorry for my lack of experience in python, the library and my poor English.

Thanks

**Comment by ferpuyol** [comment]
Sorry, didn't see that, i'll take a look. Thanks

**Comment by davidmezzetti** [comment]
Feel free to re-open if there are further questions.
