### ISSUE TITLE
Where can I download txtai document in PDF format?

### ISSUE THREAD

**Issue by snowuyl** [neuml/txtai#781]
I can find txtai document on https://neuml.github.io/txtai/ web page. Where can I download txtai document in PDF format?

**Comment by davidmezzetti** [comment]
That's not something that's currently available. The documentation uses mkdocs. It looks like there are plugins available to export to a single PDF file but it's not something I've ever looked at. 

You can download the docs folder and host them locally with mkdocs.

**Comment by snowuyl** [comment]
Thanks for your reply!
