### ISSUE TITLE
connect to local ollama on a different port

### ISSUE THREAD

**Issue by orinker** [neuml/txtai#783]
My ollama is running on a customized port instead of default one 11434. Is there any way to connect to it with txtai? 

Something like : llm = LLM("ollama/llama3:8b?url=localhost:3000") ?

**Comment by davidmezzetti** [comment]
Hello. The txtai LLM pipeline uses LiteLLM to connect to API services. To connect to a different port:

```python
llm = LLM("ollama/llama3:8b", api_base="http://localhost:3000")
```

[This configuration page](https://docs.litellm.ai/docs/providers/ollama#using-ollama-apichat) has more information on the options available for Ollama.

**Comment by davidmezzetti** [comment]
Closing this as I believe the question has been answered. Please re-open if there are further questions.
