### ISSUE TITLE
`Embeddings` local files location

### ISSUE THREAD

**Issue by francesshei** [neuml/txtai#788]
This might be a very trivial question, but where are HuggingFace `Embeddings` models stored? For instance, where are the `model..safetensors` and the other files pulled from `sentence-transformers/nli-mpnet-base-v2` after the first time `Embeddings.index()` is called?

**Comment by davidmezzetti** [comment]
Hello.

The model cache location defaults to `~/.cache/huggingface`. 

More on this can be read here: https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables#hfhome

**Comment by francesshei** [comment]
Thank you! Sorry about opening an issue for this, I couldn't find it on `txtai` docs
