### ISSUE TITLE
ImportError: cannot import name 'DuckDuckGoSearchTool' from 'transformers.agents'

### ISSUE THREAD

**Issue by blacksmithop** [neuml/txtai#807]
When running the first example on Google Colab [01_Introducing_txtai.ipynb](https://colab.research.google.com/github/neuml/txtai/blob/master/examples/01_Introducing_txtai.ipynb)
I am receiving the following error.

> ImportError: cannot import name 'DuckDuckGoSearchTool' from 'transformers.agents' (/usr/local/lib/python3.10/dist-packages/transformers/agents/__init__.py)

Digging through the source code I found [this](https://github.com/huggingface/transformers/blob/33eef992503689ba1af98090e26d3e98865b2a9b/src/transformers/agents/search.py#L25-L34) however, installing `duckduckgo_search` does not seem to fix the error. Any help would be appreciated!

**Comment by blacksmithop** [comment]
Updating `duckduckgo_search` and `transformers` and then restarting the session seems to have fixed the issue. Perhaps its an issue with the default colab version of `transformers`

**Comment by davidmezzetti** [comment]
Thanks for reporting. Can you try again with a fresh notebook? It should now automatically upgrade to the latest version of transformers. This code shouldn't require duckduckgo_search unless using the agent tool.
