### ISSUE TITLE
Add remove node to RDBMS Graph

### ISSUE THREAD

**Issue by davidmezzetti** [neuml/txtai#833]
Currently, the [upstream library](https://github.com/aplbrain/grand) doesn't have support for removing nodes. There is a [PR adding it](https://github.com/aplbrain/grand/pull/58) but in the meantime this change will add the capability.

**Comment by j6k4m8** [comment]
sounds like a silly omission for the upstream library! :)

**Comment by j6k4m8** [comment]
Thank you for https://github.com/aplbrain/grand/pull/58! 

`delete_node` is now available in [v0.5.3](https://pypi.org/project/grand-graph/0.5.3/) on PyPI:

```
pip install -U grand-graph
```

**Comment by davidmezzetti** [comment]
@j6k4m8: Wow, that was fast! I appreciate you getting a release out! I'll be able to close this as OBE now. Thank you for the help!
