### ISSUE TITLE
embeddings.index(images()) TypeError __array__() takes 1 positional argument but 2 were given 

### ISSUE THREAD

**Issue by cosmo4412** [neuml/txtai#93]
TypeError                                 Traceback (most recent call last)
<ipython-input-16-96629dc55c40> in <module>()
     11 
     12 embeddings = Embeddings({"method": "transformers", "path": "clip-ViT-B-32", "modelhub": False})
---> 13 embeddings.index(images())

9 frames
/usr/local/lib/python3.7/dist-packages/txtai/embeddings/base.py in index(self, documents)
     71 
     72         # Transform documents to embeddings vectors
---> 73         ids, dimensions, embeddings = self.vectors(documents)
     74 
     75         # Build LSA model (if enabled). Remove principal components from embeddings.

/usr/local/lib/python3.7/dist-packages/txtai/embeddings/base.py in vectors(self, documents)
    394 
    395         # Transform documents to embeddings vectors
--> 396         ids, dimensions, stream = self.model.index(documents)
    397 
    398         # Load streamed embeddings back to memory

/usr/local/lib/python3.7/dist-packages/txtai/vectors/transformers.py in index(self, documents)
     55             # Final batch
     56             if batch:
---> 57                 uids, dimensions = self.batch(batch, output)
     58                 ids.extend(uids)
     59 

/usr/local/lib/python3.7/dist-packages/txtai/vectors/transformers.py in batch(self, documents, output)
     82 
     83         # Build embeddings
---> 84         embeddings = self.model.encode(documents, show_progress_bar=False)
     85         for embedding in embeddings:
     86             if not dimensions:

/usr/local/lib/python3.7/dist-packages/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    154         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    155             sentences_batch = sentences_sorted[start_index:start_index+batch_size]
--> 156             features = self.tokenize(sentences_batch)
    157             features = batch_to_device(features, device)
    158 

/usr/local/lib/python3.7/dist-packages/sentence_transformers/SentenceTransformer.py in tokenize(self, texts)
    307         Tokenizes the texts
    308         """
--> 309         return self._first_module().tokenize(texts)
    310 
    311     def get_sentence_features(self, *features):

/usr/local/lib/python3.7/dist-packages/sentence_transformers/models/CLIPModel.py in tokenize(self, texts)
     31         for idx, data in enumerate(texts):
     32             if isinstance(data, ImageFile.ImageFile):       #An Image
---> 33                 image_features.append(self.preprocess(data).unsqueeze(0))
     34                 image_text_info.append(0)
     35             elif isinstance(data, torch.Tensor):    #A preprocessed image

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py in __call__(self, img)
     58     def __call__(self, img):
     59         for t in self.transforms:
---> 60             img = t(img)
     61         return img
     62 

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py in __call__(self, pic)
     95             Tensor: Converted image.
     96         """
---> 97         return F.to_tensor(pic)
     98 
     99     def __repr__(self):

/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py in to_tensor(pic)
    127     mode_to_nptype = {'I': np.int32, 'I;16': np.int16, 'F': np.float32}
    128     img = torch.from_numpy(
--> 129         np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
    130     )
    131 

TypeError: __array__() takes 1 positional argument but 2 were given

**Comment by davidmezzetti** [comment]
Thank you for reporting this issue. It is assumed you're running code or similar code to this notebook: https://github.com/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb

We'll look into the issue. In the meantime, you may be able to work around it by installing an older version of sentence-transformers.

```
pip install sentence-transformers==1.0.3
```

**Comment by cosmo4412** [comment]
I am still getting the same error

**Comment by davidmezzetti** [comment]
Are you able to run this notebook? - https://colab.research.google.com/github/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb

**Comment by davidmezzetti** [comment]
This notebook has been updated:  https://colab.research.google.com/github/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb

Confirmed everything is working with latest version of libraries, going to close this. Re-open if there is more data that can be provided.
