### ISSUE TITLE
Return sentences by Search

### ISSUE THREAD

**Issue by chnlyi** [neuml/txtai#94]
in order to highlight the text in the search results, is there a way to modify search function in class embedding so that the specific sentences will be returned?

**Comment by davidmezzetti** [comment]
Currently, it is assumed that content is externally stored. The index will return unique ids that can be used to resolve the matching documents.

In the future, txtai may add a default data storage capability using SQLite or something similar. [paperai](https://github.com/neuml/paperai) and [tldrstory](https://github.com/neuml/tldrstory) both use SQLite for data storage and txtai for indexing.

**Comment by chnlyi** [comment]
For documents that have multiple sentences, are multiple vectors generated to representing them?
Or there is only one vector per document?

**Comment by davidmezzetti** [comment]
One vector per document. You can split the content into sentences and index each sentence as a document. The same uid can be used for both sentences. 

Example: 

```python
embeddings.index([
  (id1, sentence1, None), 
  (id1, sentence2, None)
])
```

[Segmentation pipelines](https://neuml.github.io/txtai/pipelines/segmentation.html) can split text.

```python
from txtai.pipeline import Segmentation

segment = Segmentation(sentences=True)
segment("This is sentence1. And another sentence")
```

There is also the [Textractor](https://neuml.github.io/txtai/pipelines/textractor.html) pipeline if your working with binary documents (Word, PDF..). 

[Workflows](https://neuml.github.io/txtai/workflows.html) can join this all together into a single indexing flow. More examples below. 

https://colab.research.google.com/github/neuml/txtai/blob/master/examples/10_Extract_text_from_documents.ipynb
https://colab.research.google.com/github/neuml/txtai/blob/master/examples/14_Run_pipeline_workflows.ipynb
https://github.com/neuml/txtai/blob/master/examples/workflows.py

**Comment by davidmezzetti** [comment]
Are you able to run this notebook? - https://colab.research.google.com/github/neuml/txtai/blob/master/examples/13_Similarity_search_with_images.ipynb

**Comment by davidmezzetti** [comment]
Going to close this due to inactivity.

**Comment by davidmezzetti** [comment]
#168 will add this functionality
